### ISSUE TITLE
Map Count Error

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#101]
Location: https://spicygreenbook.org/biz/cannacakebabe-vegan-treats
Location: Home Page Map

Problem: The map states we have two listings in Las Vegas, NV. We only have one

<img width="1361" alt="Screen Shot 2020-11-11 at 8 48 10 PM" src="https://user-images.githubusercontent.com/69876068/98897037-4dc23b80-245f-11eb-93bf-081c366c6994.png">

OS: [iOS]
Browser [chrome]

**Comment by pleaseshutup** [comment]
Lady on the rocks is listed as in nevada but does not have geocoordinates setup so does now show up in the list for that city when clicked. Either remove her address as las vegas, NV or add the geocoordinates to the listing. This is fixed in prismic and not the code.
