### ISSUE TITLE
Count Error

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#102]
We are missing one listing. 

I am unable to give further directions as I don't know what happened or which one was lost. I do know that at some point last night we went minus one. I keep track of the numbers of listings we have and somehow we went backwards as I was checking on the site. Hopefully someone is able to find which one is missing.

**Comment by pleaseshutup** [comment]
This is a matter of figuring it out with what is in prismic. We don't really have a way to find this out. Primic has versions that you can investigate from days ago.

Prismic also has an import/export feature you can use to archive your data from time to time. I recommend you download it and keep a copy locally so you're not at the mercy of a 3rd party holding your data hostage.
https://spicygreenbook.prismic.io/settings/import/
