### ISSUE TITLE
Browsing Map Image Broken

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#104]
Location: https://spicygreenbook.org/search  See map on the right of the screen

Problem: When you click on **some** of the icons. The image is broken. It is supposed to display an image of the listing. Screenshots show broken vs what it's supposed to display. 

<img width="1440" alt="Screen Shot 2020-11-11 at 11 19 34 PM" src="https://user-images.githubusercontent.com/69876068/98908134-d0092a80-2474-11eb-8737-1a0a274f04ba.png">

<img width="1440" alt="Screen Shot 2020-11-11 at 11 23 10 PM" src="https://user-images.githubusercontent.com/69876068/98908251-fcbd4200-2474-11eb-9174-5005fb669b80.png">

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]

**Comment by pleaseshutup** [comment]
If this happens sometimes, but then you go back and the image loads fine my guess is that this is a temporary network issue and not a bug in the code. It is likely a spotty internet connection issue. Logically either the images work or they do not, if they randomly do not work in rare occasion that leads me to believe your network is the issue and not something we can fix.

Open this issue again if you can find one that consistently doesn't load or you can replicate the issue for us.
