### ISSUE TITLE
Website: Changes to the footer

### ISSUE THREAD

**Issue by lorenitademani** [spicygreenbook/greenbook-app#106]
Changes to the footer to remove redundant menu options. 

See pic for more details.

![Remove_Bottom_menu](https://user-images.githubusercontent.com/73954798/98967791-e2b64a80-24da-11eb-9887-5b701de452c7.jpg)

**Comment by pleaseshutup** [comment]
Hi,

Could you please join our slack in the #product channel to discuss your ideas before creating issues? We'd like to keep this area clean and have only issues ready for a developer to take on. We have a lot of various volunteers from different locations and they might end up performing work that we haven't agreed upon that needs to happen.
