### ISSUE TITLE
iPhone error

### ISSUE THREAD

**Issue by kennamcleod** [spicygreenbook/greenbook-app#108]
**Describe the bug**
website does not render without error on iPhone

**To Reproduce**
1. type in www.spicygreenbook.org in safari browser
2. receive error - cannot open the page because server cannot be found

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by its-nate** [comment]
@pleaseshutup just tried on my phone and I am not getting this error. iPhone X, iOS 14.2, Safari. Maybe it was a DNS thing since it looks like you had just directed the .org to the site a couple days ago?

**Comment by pleaseshutup** [comment]
@its-nate i've heard this bug mentioned a few times from different people but have been unable to replicate it myself. I added the .org domain but am not enforcing redirects so that should not be a factor.

**Comment by pleaseshutup** [comment]
@kennamcleod we've made some changes can you try to replicate this bug for us again? It may be resolved now. If you can replicate it, re-open the ticket and we'll get someone to investigate further.

**Comment by kennamcleod** [comment]
iPhone error  - I still get the issue.  Could it somehow be my iPhone?  I'm attaching a screenshot.
![httpsspicygreenbook org](https://user-images.githubusercontent.com/74374804/99189899-931d8c00-2731-11eb-950c-18006eef1aa4.png)

**Comment by pleaseshutup** [comment]
Closing again, we've had lots of work since this and don't seem to have anyone reporting this issue anymore.

**Comment by pleaseshutup** [comment]
Re-opening:
Per Anne Craig:
Hi Dan. I cannot remember how to put a web issue in GitHub. I continually have problems loading website on iPhone Safari. A friend just wrote me that she sent link to 2 friends with iPhones and it is crashing on their phone as well. Her Android is working fine.


NOTE: I (dan) do not have easy access to an iphone so I can't test this.

**Comment by JeroenGoddijn** [comment]
Is this still a thing/issue?
Has anyone with an iPhone or emulator figured out what is causing it (i.e. iOS version below X, or Safari version below Y)???

Since it's been open for 2 months with no solution, and already another month since it's been reopened, I'm just wondering if this issue can be closed or not...

**Comment by pleaseshutup** [comment]
Bug confirm fixed by Anne Craig via slack
