### ISSUE TITLE
SEO: Font loading blocks page content rendering on server

### ISSUE THREAD

**Issue by danielpquinn** [spicygreenbook/greenbook-app#111]
**Describe the bug**
With JavaScript disabled, the website will show a blank page with "loading", which is bad for SEO, especially for a content heavy site like this one.

**To Reproduce**
1. Open dev tools and disable JavaScript
2. Navigate to https://spicygreenbook.com

**Expected behavior**
Server renders page content so crawlers can index it and people can find businesses using google

**Screenshots**
<img width="570" alt="image" src="https://user-images.githubusercontent.com/300894/99017860-a7813f00-250d-11eb-81d7-812c120cfd7d.png">

**Desktop (please complete the following information):**
 - Not specific to any platform

**Smartphone (please complete the following information):**
 - Not specific to any platform

**Additional context**
<img width="793" alt="image" src="https://user-images.githubusercontent.com/300894/99018117-342bfd00-250e-11eb-9d9b-9de076dc8714.png">

**Comment by pleaseshutup** [comment]
i'm taking this one

**Comment by pleaseshutup** [comment]
fixed in f9c86ce36fe06a9c51c18efdd4a3d4c20413c424 and ecd524587c847cef9b0cce97ee24b9b15379ddea

We probably still need to deal with FOUT 

The trick for server side rendered pages was to ignore the fontsLoading flag on the server side (next.js thing)

**Comment by pleaseshutup** [comment]
after deploying it seems the fix did not work. dang.

**Comment by danielpquinn** [comment]
It seems to be working for me, are you sure? The site feels a lot more snappy!

**Comment by pleaseshutup** [comment]
I think I got it now.
Took a lot of work.

43bce22bb4c7fdd6509652f6196aeacc6b40df45
