### ISSUE TITLE
URGENT: Add Request URL 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#112]
The url for our add request form is https://www.spicygreenbook.org/add-request

We need this to be https://www.spicygreeenbook.org/add

**Comment by pleaseshutup** [comment]
THIS IS YOUR OWN FAULT

also this is still deploying so give it a few mins from the timestamp on this post.


fixed in 70b799b92ab6d5ac374bc26406b9b2d8d85aa846

**Comment by danilobatson** [comment]
Hahaha thanks
