### ISSUE TITLE
Mobile web menu is blank

### ISSUE THREAD

**Issue by danielpquinn** [spicygreenbook/greenbook-app#117]
**Describe the bug**
When I open the site on my phone and tap on the menu icon, I end up with a blank screen.

**To Reproduce**
1. Open spicygreenbook.com on your phone
2. Click on the menu icon in the header

**Expected behavior**
A list of menu items appear

**Screenshots**
Screenshot would just be a blank white screen
<img width="450" alt="image" src="https://user-images.githubusercontent.com/300894/99153332-bd514a00-265c-11eb-97f1-f4960272ef16.png">

**Desktop (please complete the following information):**
 - Desktop nav is still working as expected

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Browser: Mobile Chrome

**Comment by pleaseshutup** [comment]
fixed in 43bce22bb4c7fdd6509652f6196aeacc6b40df45
had to do with server side rendering of pages were always trying to render the home page because the context of which url you are on was not being set on the server side when building the static pages
