### ISSUE TITLE
Footer Name 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#126]
**Describe the bug**
The footer says "Join"

Would like to change this to "Add Listing" to match the nav

![image](https://user-images.githubusercontent.com/69876068/99343001-eb43b380-2841-11eb-8bdd-f62deb7de364.png)

**Comment by amandeswal10** [comment]
Heads up. I'll be working on resolving this bug.

**Comment by gabrielhicks** [comment]
I would also be interested in helping with this issue

**Comment by pleaseshutup** [comment]
@gabrielhicks go for it. If someone says they want to handle it and doesn't follow up within a couple of days then just assume they forgot and/or quit.

**Comment by gabrielhicks** [comment]
@pleaseshutup Okay, thanks! Just for clarification, Join will be replaced with Add Listing?

**Comment by pleaseshutup** [comment]
Yeap

**Comment by amandeswal10** [comment]
I apologize for not updating. I was working on it a bit slower due to exams at school and being new to Next.js.

**Comment by mrvncaragay** [comment]
resolve in #141
