### ISSUE TITLE
App Link Incorrect 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#127]
**Describe the bug**
In the Spicy Green Book app. 

The menu button on the top right brings up the menu on the side and one of the options says "Process"

Clicking it will actually take you to the "About" page instead of the "Process" page. 

**To Reproduce**
1. Open the app
2. Click on menu in the top right 
3. Click "Process"

**Expected behavior**
Should take you to the "Process" page

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]

**Comment by mrvncaragay** [comment]
Thanks @danilobatson, I will resolve this

**Comment by mrvncaragay** [comment]
@pleaseshutup, in the screens/Process.js uid was set to 'about', but when i changed it to process. I get an empty data. any thoughts on this? I tested other url such as contact and it works fine.
![Screen Shot 2020-11-16 at 9 42 44 PM](https://user-images.githubusercontent.com/1195427/99351141-ca388e00-2854-11eb-9544-54b98d1b9982.png)

**Comment by pleaseshutup** [comment]
Try 'our-process' And if that fails update this ticket and I'll check it out again in the morning

**Comment by mrvncaragay** [comment]
@pleaseshutup it works! thanks

**Comment by mrvncaragay** [comment]
resolve this issue on 991e9dbfc97e66753c1db8f192fad80436bd65cb
