### ISSUE TITLE
App Homepage 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#128]
**Describe the bug**
The map on the homepage is not interactive like it is on the website. Clicking on the map does nothing. 

**To Reproduce**
1. Open the SGB app
2. Scroll down to the map
3. Click on any state

**Expected behavior**
Map should be interactive where clicking on a state will show a pop up of cities that have businesses listed in its respective state. 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]

**Comment by pleaseshutup** [comment]
<TouchableOpacity> doesn't seem to work on SVG nodes.
I am not quite sure how to handle this for mobile apps unless an overall on press event can let you see which node was tapped we can get the ID from it to determine which state.

Just my notes if someone tries to tackle this before I get to it.

**Comment by mrvncaragay** [comment]
Will work on this issue.

**Comment by mrvncaragay** [comment]
this issue was resolve in this 43b6651b2b39f975020df6862af51e7ecf488968
