### ISSUE TITLE
App Footer 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#129]
**Describe the bug**
_See screenshot_ 

On the app. 

The graphic on the bottom says "Join"

This should say "Add Listing" 

**To Reproduce**
1. Open the app
2. Click on third graphic in the footer
3. Will read "Join"

**Expected behavior**
Should read "Add Listing" 

![image](https://user-images.githubusercontent.com/69876068/99345204-a53d1e80-2846-11eb-96fa-583aca6b9f24.png)

**Smartphone (please complete the following information):**
 - Device: [iPhone 11]

**Comment by mrvncaragay** [comment]
I will fix this too, thanks!

**Comment by mrvncaragay** [comment]
Hi @danilobatson  #113 resolve this issue.
