### ISSUE TITLE
PC vs Mac 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#13]
Looking at sky gourmet tacos through screen share. 

On the mac can see the zoomed out photo of the tacos to get a more complete picture. 

While PC is too zoomed in and you can only see the very top of the tacos

**Comment by pleaseshutup** [comment]
Is this a duplicate of:
https://github.com/spicygreenbook/greenbook-app/issues/11

the difference isn't pc or mac it is the screen size thus the aspect ratio and where the image gets cropped.

**Comment by pleaseshutup** [comment]
resolved by choosing diff images. it's the forced aspect ratio in the design.
