### ISSUE TITLE
App Contact From 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#130]
**Describe the bug**

On the app. 

"Go To Contact Form" takes you to https://spicygreenbook.com/contact

This should go to https://spicygreenbook.org/contact

**To Reproduce**
1. Open the app
2. Click on menu in the top right
3. Click contact
4. Scroll down
5. Click "Go To Contact Form"
6. See Error
**Expected behavior**

This should go to https://spicygreenbook.org/contact

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]

**Comment by pleaseshutup** [comment]
handled in deb48cd03098f62642245e4cd49e66d505cd3abc and google search console updated to reflect the new domain.
