### ISSUE TITLE
App Add Listing

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#132]
**Describe the bug**

On the app. 

"Go To Donation Form" takes you to https://spicygreenbook.com/add

This should go to https://spicygreenbook.org/add

**To Reproduce**
1. Open the app
2. Click on the third graphic in the footer
3. Click "Go To Add Listing Form"
4. See Error

**Expected behavior**

This should go to https://spicygreenbook.org/add

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]

**Comment by pleaseshutup** [comment]
handled in deb48cd03098f62642245e4cd49e66d505cd3abc and google search console updated to reflect the new domain.
