### ISSUE TITLE
Location API

### ISSUE THREAD

**Issue by pleaseshutup** [spicygreenbook/greenbook-app#137]
Lets use a service like https://ipstack.com/ and the pages/api functionality of vercel (serverless functions, see api/geocode.js for example) 

We can pre-fill the users location with a city/state like yelp does. Would be ideal to build our own cache the same way geocode.js does it so we only use our api credits on unique lookups and never repeat lookups. 

We could even distribute the requests over multiple different free api's to find a users city/state based on their IP. 

When a user types in an address and/or uses the (work in progress) "Current Location" feature we should cache that in localStorage so it's always pre-filled w/o a network or location request.

Ideally we have our own service that:
1 - allows us to get a location based on the user's ip (cached)
2 - allows us to reverse lookup geocoordinates for use in determining city/state when we get their coords (cached)
3 - allows us to get the geocoodinates from a city/state/location input (existing functionality of geocode.js)

**Comment by rossedwardsus** [comment]
Hello.  You wouldn't use ip addresses for these but rather you would use geolocation, which in a browser is not that precise but should work well enough providing your data has latitude and longitude.  In truth you should have a mobile app so you can access the chips that are built in to them that provide very precise location information.

**Comment by pleaseshutup** [comment]
This is for guessing the user's location when ip address is the only information we have. Before the client is loaded and not on a mobile device or browser with the feature enabled.

**Comment by pleaseshutup** [comment]
i'll do this now

**Comment by rossedwardsus** [comment]
Ip address is often inaccurate due to the way that networks work.  You can use geolocation on the browser however web based geolocation is not as accurate as native is.  It might be good enough though.

**Comment by pleaseshutup** [comment]
Thanks @rossedwardsus we're doing this in addition to that feature already implemented.
