### ISSUE TITLE
Home page layout broken on mobile web

### ISSUE THREAD

**Issue by danielpquinn** [spicygreenbook/greenbook-app#143]
**Describe the bug**
Home page layout doesn't look right on mobile web, see screenshot. I think I fixed this issue once before by forcing the page to refresh after initial load. If there's a cleaner way to fix the issue that would be great!

**To Reproduce**
1. Load the home page on spicygreenbook.com

**Screenshots**
![image](https://user-images.githubusercontent.com/300894/99911094-ff0a7200-2ca6-11eb-938b-abaa0145b29a.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android
 - Browser Chrome
 - Version Latest

**Comment by mrvncaragay** [comment]
@danielpquinn hmm testing this on my local build and it looks normal to me.
