### ISSUE TITLE
IOS expo bug, store listings not opening on press

### ISSUE THREAD

**Issue by Arax1** [spicygreenbook/greenbook-app#145]
**Describe the bug**
The bug is mainly found when trying to test the mobile app on an IOS simulator through expo. While you are browsing through
the businesses, clicking on the business doesn't lead to the image and store listings as expected. Instead it gives an error saying it could not parse the array object. 

This bug is only when testing through Expo mobile

**To Reproduce**
1. Expo Start
2. Run the mobile app using Expo (I used IOS, not sure if this is a problem on Android)
3. Once open, click the search icon on the bottom of the screen to browse
4. Clicking on any of the businesses doesn't do anything, and you get the error. 

**Screenshots**
![Ios expo error](https://user-images.githubusercontent.com/28972415/99918248-97bee300-2ce3-11eb-86cd-4fbfd685d6be.png)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS

**Comment by mrvncaragay** [comment]
@Arax1 does this issue still persist? thanks!

**Comment by Arax1** [comment]
@mrvncaragay You fixed the issue where the businesses now go to the landing page, which is good! But when you click on one of the images to go to the image gallery it doesn't go to the image gallery.

This is the response i get in the log whenever I press on one of the images.
![Error spicygreenbook expo 2](https://user-images.githubusercontent.com/28972415/100556450-8d1ac580-3270-11eb-9974-4afe06addd40.png)

If this issue is caused by something in the image gallery let me know, and thank you!

**Comment by mrvncaragay** [comment]
Hey @Arax1 thanks for confirming. Yea image gallery works fine on web but not on native  environment. We can prolly just render the Image Gallery component in Listing component when user click on the images using the isWeb check. or create new Component specifically just for native environment.
