### ISSUE TITLE
URGENT: Volunteer Form Is Missing

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#152]
**Describe the bug**
There is no link to the volunteer form on the volunteer page

**To Reproduce**
1. Go to 'www.spicygreenbook.org/volunteer'
2. Scroll down to the bottom
3. See error

**Expected behavior**
A link to fill out the volunteer form

**Comment by mrvncaragay** [comment]
I will look into this, thanks!
