### ISSUE TITLE
Press Logo Homepage 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#154]
Would like to add the logo of Tech Bites Podcast to be added to the home page press area. 

Linked to the following: https://podcasts.apple.com/us/podcast/spicy-green-book-non-profit-directory-black-owned-restaurants/id960833354?i=1000499037556

<img width="1440" alt="Screen Shot 2020-11-30 at 4 26 10 PM" src="https://user-images.githubusercontent.com/69876068/100681669-1beb1900-3329-11eb-87e8-b455e3653b64.png">

<img width="330" alt="Screen Shot 2020-11-17 at 1 50 17 PM" src="https://user-images.githubusercontent.com/69876068/100681656-168dce80-3329-11eb-920a-141a4d108a96.png">

**Comment by pleaseshutup** [comment]
This is handled by adding an element in prismic in the press section. Let us know if you want something different.
