### ISSUE TITLE
About Us Page Redesign 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#155]
Design pictured below 

Please no longer use content from prismic and implement this design as is and use your best judgement to make it also look good on mobile sized screens. Don't forget to test on web and mobile apps.

![image](https://user-images.githubusercontent.com/69876068/100904095-83b17900-347b-11eb-89c2-7eeb6cc49453.png)

**Comment by straightupcoding** [comment]
I will work on this redesign.

**Comment by pleaseshutup** [comment]
@straightupcoding is still working on this, he's updating us in slack.

**Comment by pleaseshutup** [comment]
This is done. Thanks @straightupcoding
