### ISSUE TITLE
Contact Us Page Redesign 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#156]
Design pictured below 

Please no longer use content from prismic and implement this design as is and use your best judgement to make it also look good on mobile sized screens. Don't forget to test on web and mobile apps

![image](https://user-images.githubusercontent.com/69876068/100904708-1d792600-347c-11eb-98f0-4a34be8ba16f.png)

**Comment by pleaseshutup** [comment]
Whomever takes this task.

I think you can still use the prismic content. Just put the data from prismic on the left side there and statically add the image below/the shadow box. Then put the contact form on the right side. For mobile they just stack and the form is under the content. 

The prismic content is the content in the <RichText /> component already in there.

**Comment by rrajra** [comment]
I'll start working on this.

**Comment by pleaseshutup** [comment]
@rrajra let us know a status on this if you can finish it or someone else should jump on it

**Comment by rrajra** [comment]
@pleaseshutup should be finished with this today

**Comment by pleaseshutup** [comment]
Hows it going? Jump into slack if you have any questions!

**Comment by danilobatson** [comment]
@rrajra any updates on this?

**Comment by rrajra** [comment]
Sorry, had to go out of state for a little. It’s done.

**Comment by danilobatson** [comment]
I don't see it on the site. Has is been deployed

**Comment by rrajra** [comment]
Sorry for the delay, just got home. I forked the main repo and the updated contact page is there.

**Comment by pleaseshutup** [comment]
@rrajra could you please make a PR? In the main readme of this repo there is some instructions on how to do that.

also please validate that your fixes look good on mobile/desktop web as well as native mobile apps via expo.

**Comment by danilobatson** [comment]
@rrajra @pleaseshutup is this task complete?

**Comment by JeroenGoddijn** [comment]
@rrajra Make sure you push it to the origin: `git push origin master` where you can replace "master" with your branch name that contains the update. Potentially your  work is saved in your forked repository, but not pushed to the main SGB repository...

**Comment by danilobatson** [comment]
@rrajra Following up on updates for this task

**Comment by pleaseshutup** [comment]
This task is available for someone to complete. Previous volunteer developer has not updated in a while, assumed to be abandoned. Please pick up this task if you like.

**Comment by kyoga99** [comment]
@pleaseshutup is this task still available?

**Comment by pleaseshutup** [comment]
@kyoga99 yeap have at it!

The previous developer went dark so I don't think there will be any progress to work from. Seems like they did the work but couldn't pass that final hurdle of doing a PR.

**Comment by kyoga99** [comment]
@pleaseshutup I finished the page, but I was wondering how to get access to that exact picture. I also wanted to know if I should test the contact form to make sure it still works (although I didn't touch the functionality at all).

**Comment by pleaseshutup** [comment]
@kyoga99 I would ask in slack in the developer or product channels... Maybe @danilobatson knows who designed this so we know who to contact for the image files?

The form itself is from honeybook, you can do a quick test to see it still works but if it renders it's probably ok.

**Comment by danilobatson** [comment]
@kyoga99 @pleaseshutup I don't remember that photo or who designed it but I will just give you another image to use

**Comment by danilobatson** [comment]
@kyoga99 try one of these


![DSC_5220](https://user-images.githubusercontent.com/69876068/118738318-9803eb00-b7fb-11eb-945b-1236d4631fe2.jpg)
![DSC_5304](https://user-images.githubusercontent.com/69876068/118738321-9afedb80-b7fb-11eb-966d-222c4a867f91.jpg)

**Comment by kyoga99** [comment]
Thank you!

**Comment by kyoga99** [comment]
@pleaseshutup I noticed that when I use expo to test, the contact form does not show up, even without any of the modifications I made.

**Comment by pleaseshutup** [comment]
@kyoga99 
Those contact forms only work on web. What we have usually done on native is link them to the same page/route on web.
So do a switch for when they are on native to just be a button to go to the form and on the web the form should display fine.

**Comment by kyoga99** [comment]
@danilobatson should the url for questions about photography open up the email app for the user? The slack url doesn't take the user anywhere unless they are already a member of the slack, is that the correct functionality?

**Comment by danilobatson** [comment]
@kyoga99 yea it should open to email and take the slack off

**Comment by kyoga99** [comment]
@pleaseshutup should this issue be closed? I believe the pull request for it was approved.

**Comment by mrvncaragay** [comment]
Thanks @kyoga99, will closed this now.
