### ISSUE TITLE
Home Page App Add 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#158]
Hoping to promote our app more. Can we change the home page to list this above in the header and right above the press links. Note the mockup. 

<img width="760" alt="Screen Shot 2020-12-04 at 9 26 01 AM" src="https://user-images.githubusercontent.com/69876068/101555837-4878e380-396e-11eb-96d8-9ce01d1e8a44.png">

**Comment by danilobatson** [comment]
The "Download Our App" in the header should probably just scroll to the part of the home page where they can click either app store or google play store that exist above the press logos

**Comment by mrvncaragay** [comment]
will work on this enchancement.

**Comment by mrvncaragay** [comment]
@danilobatson do you want the "Download Our App" in the header to show on every screens (Donate, Volunteer...)? or just in Home screen.
