### ISSUE TITLE
Feature: Volunteer Page Redesign 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#16]
![SGB-Volunteer-opened](https://user-images.githubusercontent.com/69876068/97482398-5a00b180-1913-11eb-822b-98eba4a9e723.jpg)
![SGB-Volunteer](https://user-images.githubusercontent.com/69876068/97482410-5d943880-1913-11eb-9694-789d22288a9e.jpg)

**Comment by pleaseshutup** [comment]
I was able to enhance the look a bit with the provided design, however, this content is managed in prismic and not controlled by the front-end code so it will be quite challenging to take the prismic content and output this. Not impossible but we'll just mark this as progress made and more to do.

**Comment by pleaseshutup** [comment]
To finish this:
step 1. create new type in prismic for each volunteer position
step 2. remove each position from vounteer content page in prismic
step 3. make the collapsible sections come from the volunteers new data type in prismic
step 4: profit

**Comment by Arax1** [comment]
I will help with this issue and the re-design

**Comment by mrvncaragay** [comment]
@Arax1 can we close this one too?

**Comment by Arax1** [comment]
Done for now.
