### ISSUE TITLE
Volunteer Page Infographic

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#160]
**Describe the bug**
The infographic on the volunteer page is too big. At 100% it is too large to consume. I zoomed out to 50% just to get the screenshot. I would like to resize it smaller where this info is consumable. 
**To Reproduce**
1. Go to 'spicygreenbook.org/volunteer'
2. See error

**Screenshots**
<img width="1440" alt="Screen Shot 2020-12-09 at 7 49 03 AM" src="https://user-images.githubusercontent.com/69876068/101652740-75230e80-39f3-11eb-93ea-ee0af0391729.png">

**Desktop (please complete the following information):**
 - iOS]
 - Chrome

**Comment by Arax1** [comment]
Because this is about the volunteer page, I'll try and resize the infographic to fit into the new design

**Comment by danilobatson** [comment]
Great, thank you
