### ISSUE TITLE
Instagram Thread Not Present 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#161]
**Describe the bug**
The photos from the Instagram are not on the homepage anymore. 

**To Reproduce**
1. Go to 'spicygreenbook.org'
2.  Scroll down to the bottom right below @spicygreenbook 
3. See error

**Expected behavior**
Should be a thread of our recent photos on IG

**Screenshots**

![image](https://user-images.githubusercontent.com/69876068/101788713-453c3f80-3ab5-11eb-99ae-74e614904fb5.png)

**Desktop (please complete the following information):**
 -  iOS
 - chrome

**Comment by pleaseshutup** [comment]
fixed in fe36a55ee172ed1ad97077f4d9773e236e883956

devs stop disabling it!!
