### ISSUE TITLE
Add Listing Page 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#162]
Would like to modify the add listing page to the image below. 

The hyperlink for "Fill Out Form" should go to this link: https://www.honeybook.com/widget/spicy_green_book_159485/cf_id/5f6bf5318be9f533980593fa

Here is the figma if you prefer instead of a screenshot: 
https://www.figma.com/file/aEeUdhgwUqOAk9aC0egEuh/SGB?node-id=4%3A2

![image](https://user-images.githubusercontent.com/69876068/101828381-505b9380-3ae6-11eb-990c-ae38058c9c0c.png)

**Comment by mrvncaragay** [comment]
I will work on this task.

**Comment by danilobatson** [comment]
@mrvncaragay I can probably get a photo of the infographic to put on prismic but I can't do the bottom half with the photo and the links

**Comment by mrvncaragay** [comment]
@danilobatson okay, sounds good. will work on the bottom part.

**Comment by danilobatson** [comment]
@mrvncaragay great, the top has been adjusted.
