### ISSUE TITLE
Feature: Updates Page Redesign 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#17]
![SGB-Updates](https://user-images.githubusercontent.com/69876068/97482500-769ce980-1913-11eb-829a-4be81b9b20c7.jpg)

**Comment by pleaseshutup** [comment]
A lot of this has been handled in https://spicygreenbook.com/press if you want to reference that before implementing

**Comment by its-nate** [comment]
I can take this one.

**Comment by pleaseshutup** [comment]
@its-nate great work, thanks
