### ISSUE TITLE
Volunteers Page

### ISSUE THREAD

**Issue by pleaseshutup** [spicygreenbook/greenbook-app#171]
A page to showcase all of our volunteers and their contributions.
This is separate from the "Volunteer" page which provides information for potential volunteers. 

All of the work is setup for you. in screens/Volunteers.js this code shows a grid layout (which is just a copy of the press page) and you will be able to see the data available. Our goal here is to give credit to those who have volunteered their time and talent to Spicy Green Book and allocate a dollar amount to their efforts. This is to show how much people care about the project and inspire others to join in as well as hopefully motivate those already helping out to keep going.

We'd love to see the total contribution amount on the top and then the list of volunteers down the page with their info. We do not have a design right now so please take the first pass at getting this page up and we will eventually get a design or just slowly improve over time as needed.

**Comment by danilobatson** [comment]
Here is the design for that 

https://www.figma.com/file/Qzv2RolEDbyClN65tiHEts/Spicy-Green-Book?node-id=221%3A0

**Comment by damienaries** [comment]
Taking on this issue, first time working on this app so any advice /  suggestions are always welcome!

**Comment by mrvncaragay** [comment]
@pleaseshutup i saw your slack message in regards to this. do you need the entire page build or just the modal part?

**Comment by damienaries** [comment]
I was trying to figure out the same thing

**Comment by pleaseshutup** [comment]
Just the modal is left but feel free to touch up anything else ... Pull master and see where I left off.

**Comment by pleaseshutup** [comment]
Just the modal is left but feel free to touch up anything else ... Pull master and see where I left off.

**Comment by pleaseshutup** [comment]
i'll do the modal

**Comment by pleaseshutup** [comment]
This is done, however, I wouldn't mind if someone could clean up the look a bit to be more polished to match the provided design.

**Comment by JeroenGoddijn** [comment]
I'll work on some styling issues in page(such as settting minHeight for rows, so they all look the same even if image has different dimensions) and try to make the modal match the design more.
