### ISSUE TITLE
Testimonials page

### ISSUE THREAD

**Issue by pleaseshutup** [spicygreenbook/greenbook-app#172]
All of the work is setup here. We do not have a design so please edit/test the screens/Testimonials.js page to see the basic structure and implement as you like. Should be available on the site at /testimonials.

Once done we can link to it in the nav and footer.

**Comment by pleaseshutup** [comment]
Here is the design:
https://www.figma.com/file/Xd3J4jmrUjFosCb14JGouN/SGB?node-id=15%3A0

**Comment by danilobatson** [comment]
Updated design link:

https://www.figma.com/file/Xd3J4jmrUjFosCb14JGouN/SGB?node-id=127%3A16

**Comment by domferris** [comment]
I'll hop on this one ✅

**Comment by danilobatson** [comment]
@domferris any updates?

**Comment by domferris** [comment]
@danilobatson still working through this. Aiming to have a preview this weekend!

**Comment by pleaseshutup** [comment]
I am closing this issue because the Testimonials page was completed by someone else from a duplicate issue. The implementation did not meet the design. I am creating a new issue to resolve any conflicts and have clear direction.

**Comment by domferris** [comment]
Copy that @pleaseshutup -- let me know if I can be of assistance resolving any conflicts.

**Comment by pleaseshutup** [comment]
@domferris feel free to look at the new testimonials design and implement :-)
https://github.com/spicygreenbook/greenbook-app/issues/273
