### ISSUE TITLE
App Onboarding Slides

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#173]
Would like the implement the following design as intro for the first time download of the SGB app. 

![image](https://user-images.githubusercontent.com/69876068/102729633-56bbed80-42e6-11eb-8ad5-b029beeb8368.png)

**Comment by cshin1** [comment]
More details here below.

[01-Onboarding Assets.zip](https://github.com/spicygreenbook/greenbook-app/files/5722045/01-Onboarding.Assets.zip)

Figma file for spacing and sizes: https://www.figma.com/file/Qzv2RolEDbyClN65tiHEts/Spicy-Green-Book-Copy?node-id=206%3A0

**Comment by Arax1** [comment]
I will take up this task and see what I can do

**Comment by danilobatson** [comment]
@Arax1 any updates on this?

**Comment by pleaseshutup** [comment]
19 days without an update this task is available.

**Comment by Arax1** [comment]
The onboarding slides are finished! Sorry for lack of updates on this post. I pushed the final changes yesterday and a few minutes ago and will PR merge after review

**Comment by danilobatson** [comment]
@Arax1 @pleaseshutup Where are we on this task?

**Comment by pleaseshutup** [comment]
This is done by @Arax1
