### ISSUE TITLE
Add Listing Page Repeat

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#174]
**Describe the bug**
Text on the add listing page is repeated. 

**To Reproduce**
1. Go to www.spicygreenbook.org/add
2. Scroll down to the bottom 
3.. See error

**Expected behavior**
We should delete the copy right above the couple's photo that says "Are you ready? Let's fill out the volunteer form"

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/102823190-54fa3480-438f-11eb-958a-dfdf0b2cfc8f.png)

**Desktop (please complete the following information):**
-iOS
-Chrome

**Comment by pleaseshutup** [comment]
That text appears twice. Do you want it removed from the top (green) or next to the button?

if you want it off the top, remove it in prismic. If you want it off the left of the button, it would look strange.

@danilobatson

**Comment by danilobatson** [comment]
Got it.

**Comment by danilobatson** [comment]
@pleaseshutup actually doesn't look like that text is in prismic

**Comment by pleaseshutup** [comment]
It's in the graphic, lol. I cropped it in prismic and published.
