### ISSUE TITLE
Mobile Only (App & Website): Add Listing Page

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#175]
**Describe the bug**
Image that exist on the spicygreenbook.org/add page on the desktop is not present on mobile. Image showcases error. Go to the page on desktop to see what it is supposed to look like. 

**To Reproduce**
1. Go to spicygreenbook.org/add
2. Scroll down. 
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/102823669-30eb2300-4390-11eb-890c-22647934bd78.png)

**Smartphone (please complete the following information):**
 - iPhone 11
 - App and website

**Comment by pleaseshutup** [comment]
fixed in f0dee52bf8cfd4b24ccf908fbf961ac2122252b0
