### ISSUE TITLE
Hyperlink Text Overlay Home Page 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#176]
![image](https://user-images.githubusercontent.com/69876068/102825764-52e6a480-4394-11eb-8c8a-b4fe6f008b68.png)

Would like to implement this design on the homepage for our three call to actions. 

They should be hyper linked to go to the following pages respectively

1. https://www.spicygreenbook.org/add
2. https://www.spicygreenbook.org/donate
3. https://www.spicygreenbook.org/volunteer

**Please note that it should read "Black business" and "Black-owned" with the "B" capitalized and it should read "Become a donor" not donate**

This should go right above the "Update" section on the home page

![image](https://user-images.githubusercontent.com/69876068/102950310-396e5700-447f-11eb-910f-9b0fa485b58c.png)

**Comment by pleaseshutup** [comment]
You really want it to say "Become a Donate" ???

**Comment by danilobatson** [comment]
@pleaseshutup no in the description I noted that it should read "Become a donor" just didn't want them to make go through the trouble of editing the design on something that is easily adjustable on implementation.

**Comment by mrvncaragay** [comment]
I'm implementing this now

**Comment by danilobatson** [comment]
@mrvncaragay I don't know how to merge but the complete additions can be found on #177

**Comment by mrvncaragay** [comment]
Implemented the call to action section 4a604ecdb1bb3321189bd349bc9e926b117e804e. Closing this to reference #177 instead.
