### ISSUE TITLE
Homepage Additions 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#177]
Would like to make some changes to the the home page. See the footer, map, testimonial section, and "Become" section. 

The testimonials section would need to work as a slideshow that changes automatically but also manually (arrows as in the listing section)

![image](https://user-images.githubusercontent.com/69876068/102938201-b3431800-4460-11eb-863b-d0bded1257cf.png)

**Comment by pleaseshutup** [comment]
@danilobatson please add real testimonials. If we add this to the site without them it will look terrible.
I've updated prismic to reflect the fields presented in this design.

**Comment by danilobatson** [comment]
@pleaseshutup will do

**Comment by danilobatson** [comment]
@pleaseshutup testimonials have been updated.

**Comment by danilobatson** [comment]
Here is the content needed for this:


![four-way-fist-bump-at-work](https://user-images.githubusercontent.com/69876068/102938056-652e1480-4460-11eb-9d97-a63d237c421c.jpg)

![Photo-Frame](https://user-images.githubusercontent.com/69876068/102938089-74ad5d80-4460-11eb-8934-1990e68c4f07.png)
![PiggyBank-Small](https://user-images.githubusercontent.com/69876068/102938092-75de8a80-4460-11eb-93bf-3fb325c567b7.png)
![PiggyBank](https://user-images.githubusercontent.com/69876068/102938094-770fb780-4460-11eb-9d1b-263961b3b96e.png)
![Woman-Umbrella-Small](https://user-images.githubusercontent.com/69876068/102938108-7c6d0200-4460-11eb-8844-c84aa33b0b08.jpg)
![Woman-Umbrella](https://user-images.githubusercontent.com/69876068/102938109-7e36c580-4460-11eb-9d4d-da4000b264d1.jpg)

**Comment by mrvncaragay** [comment]
#176 is implemented 4a604ecdb1bb3321189bd349bc9e926b117e804e

**Comment by mrvncaragay** [comment]
initial implementation 200d535de67009e6c2f64fc5798dc8b5b2b7b532 has been deployed.
