### ISSUE TITLE
HIGH PRIORITY: Primsic copy issue

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#178]
**Describe the bug**
This bug happens THROUGHOUT the website for all copy managed on prismic. 

All the copy seems to have a format error every time copy is either in bold or hyperlinked. 

The copy will insert a line break right after when it shouldn't be. The image will showcase one example but this is happening on multiple web pages. 

In the example in the screenshot it would be where it says "Donate via Paypal" That should be all one line. I noticed if you hover your mouse over the "Donate via" line that the whole line where there is no text, right to the copy, exist an active link. 

**To Reproduce**
1. Go to www.spicygreenbook.org/donate
2. Scroll down to third paragraph
3. See error

**Expected behavior**
There should be no line break after bolded or hyperlinked copy

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/102840139-019bdc80-43b7-11eb-9e13-f7767c40d3c8.png)

**Desktop (please complete the following information):**
-iOS
-Chrome

**Comment by pleaseshutup** [comment]
fixed in 0c1369025caa3aca8458e20667ae0b850499ba96
