### ISSUE TITLE
Feature: Team Page Redesign

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#18]
![SGB-Team](https://user-images.githubusercontent.com/69876068/97482542-85839c00-1913-11eb-90a7-1b6926e00ead.jpg)

**Comment by MBaitz** [comment]
I would love to tackle this for you.

**Comment by danilobatson** [comment]
Here is a invite link. Please use as soon as possible as it an expiring link 

https://join.slack.com/t/spicy-green-book/shared_invite/zt-j1nb623l-Pbg4T~iNGxsVqH~he1wbWQ

**Comment by pleaseshutup** [comment]
@mrvncaragay thanks, great work
