### ISSUE TITLE
Footer Alignment

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#182]
The footer has been reorganized. 

See image. Please keep YouTube link as the last one on the social

![image](https://user-images.githubusercontent.com/69876068/102921523-5b48e900-4441-11eb-923f-55bcb1c6c424.png)

**Comment by danilobatson** [comment]
![image](https://user-images.githubusercontent.com/69876068/102950293-31aeb280-447f-11eb-8876-a2b42d220b01.png)

**Comment by pleaseshutup** [comment]
Whoever implements this design please do NOT enforce any heights on elements as that technique will not work with responsive design. As the screen gets smaller the content begins to wrap/stack more and things get taller.

**Comment by pleaseshutup** [comment]
I opted to not make the "press kit" link dark green as it was hard enough to see in the provided design
