### ISSUE TITLE
PRIORITY: App Listing Photos

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#183]
**Describe the bug**
On our app you cannot go through the gallery of photos on the listing. You can only see the first three photos on the listing but can't open it to go through the gallery. 

**To Reproduce**
1. Go to the spicy green book app
2. Click on any listing 
3. Click on any photo

**Expected behavior**
The gallery should open up for you to go through all the photos

**Comment by mrvncaragay** [comment]
@danilobatson  I implemented a basic carousel native version 1948d8ef05c4bb8d0cd6efabfb126ac4b7cb3196 

Uploading Screen Recording 2020-12-22 at 3.19.16 PM.mov…

**Comment by danilobatson** [comment]
@mrvncaragay the video didn't load and I don't see it implemented on the app yet. I don't know if you deployed it

**Comment by pleaseshutup** [comment]
the new builds will be up soon

**Comment by mrvncaragay** [comment]
This issue is now resolve with the new build.
