### ISSUE TITLE
HIGH PRIORITY: Arrows on mobile web  uy76

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#184]
**Describe the bug**
For the photo gallery the arrows are too large. The arrows need to be a lot smaller so we can see the photo of food. 

**To Reproduce**
1. Go to www.spicygreenbook.org on your phone 
2. Click on any listing
3. Open up the gallery

**Expected behavior**
Arrows need to not hamper the view of the photos. 

![image](https://user-images.githubusercontent.com/69876068/102937829-e042fb00-445f-11eb-94c8-18ee6657a5db.png)

**Comment by mrvncaragay** [comment]
I'm adjusting the caret sizes.

**Comment by mrvncaragay** [comment]
I updated the sizes here 1c000df4817d3a05a6d9bc517c069a89dc985f01. Note that app needs to be updated in app store and google play to see this change. will close for now.
