### ISSUE TITLE
PRIORITY: Merchandise Page

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#188]
Looking to design the merchandise page. 

We will be using Shopify. We can create a page on our site and embed their code to display our merch options for users to purchase from our site.

**HERE IS THE DESIGN MOCKUP**

https://www.figma.com/file/CJGYXDaErs16vy6O97oAWL/Merchandise?node-id=0%3A1

![image](https://user-images.githubusercontent.com/69876068/103123983-fbb62d80-463a-11eb-94c0-f3733e27072a.png)

*
*
*

**THE FOLLOWING PROVIDES SOME INSIGHT ON THE INTEGRATION THAT SHOPIFY SENT ME**

![image](https://user-images.githubusercontent.com/69876068/103124079-636c7880-463b-11eb-8186-cd52c4ee0650.png)

![image](https://user-images.githubusercontent.com/69876068/103124085-68c9c300-463b-11eb-8d5f-d79b4bdf637d.png)

https://user-images.githubusercontent.com/69876068/103124195-d249d180-463b-11eb-9d1f-d34a7e0aa659.mp4

Let me know when you take on this project so I can get you the buy code. This is **TIME **SENSITIVE** as there is a cost to use this feature via shopify so it is important we are allowing people to purchase merchandise to cover this cost.

**Comment by pleaseshutup** [comment]
Send me the login access to shopify so I can just figure it out.

**Comment by pleaseshutup** [comment]
Implemented
