### ISSUE TITLE
Feature: Process Page Redesign 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#19]
![SGB-Process](https://user-images.githubusercontent.com/69876068/97482592-93d1b800-1913-11eb-85d6-580bfbc9d97a.jpg)

**Comment by mrvncaragay** [comment]
i can help with this

**Comment by pleaseshutup** [comment]
@mrvncaragay please find another issue, this one ins't really feasible given that the content comes from a CMS / rich text editor and won't easily fit into this format. I am talking to the designer about a different approach
