### ISSUE TITLE
Map Issues 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#190]
**Describe the bug**
The map displays the incorrect number of states. I count 21 states. It displays 23 states

**To Reproduce**
1. Go to 'www.spicygreenbook.org
2. Scroll down to the map 
3. See error

**Expected behavior**
Should display the correct number of states 

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/103204361-0cb9a580-48ac-11eb-8f89-c0c6a18da8fc.png)

**Comment by pleaseshutup** [comment]
What's correct?

**Comment by pleaseshutup** [comment]
23 seems correct. Probably unable to see/count the smaller states like DC
