### ISSUE TITLE
Map Hyperlink 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#191]
**Describe the bug**
The entire state should be displayed hyperlinked. It seems that on the desktop when hovering over the state the mouse does not change to the hand to signify that it is hyperlinked. 

**To Reproduce**
1. Go to 'www.spicygreenbook.org'
2. Scroll down to the map
3. Hover your mouse over the map 

**Expected behavior**
Mouse should change to show that it is clickable to the use 

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/103204601-8ce00b00-48ac-11eb-9402-3d18f346f6d9.png)

**Comment by joshkwannacode** [comment]
Hey I think I fixed it, I'll push the code soon!

**Comment by mrvncaragay** [comment]
Thanks @joshkwannacode for fixing.
