### ISSUE TITLE
Home Page Testimonial Gallery 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#192]
**Describe the bug**
The testimonial section of the home page is supposed to rotate to show the several available testimonials. It currently shows only one testimonial. Note the error in the first photo and how it is supposed to be displayed in the second photo. 

**To Reproduce**
1. Go to www.spicygreenbook.org
2. Scroll down to testimonials
3. See error

**Expected behavior**
There should be arrows on the ends to manually rotate through testimonials and it should auto rotate every five seconds. 

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/103204781-eea07500-48ac-11eb-9b35-028b08241d71.png)
.
![image](https://user-images.githubusercontent.com/69876068/103204830-0d067080-48ad-11eb-85e9-14445717a174.png)

**Comment by pleaseshutup** [comment]
the testimonials swipe for me. check again? close if done.

**Comment by danilobatson** [comment]
Yes it was fixed.
