### ISSUE TITLE
URGENT: Donate Page 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#193]
**Describe the bug**
None of the forms to donate are listed on the page. There is supposed to be two for PayPal (subscribe vs one time payment) and another form for stripe 

**To Reproduce**
1. Go to www.spicygreenbook.org/donate
2. Scroll down to
3. See error

**Expected behavior**
Should be three places for someone to donate. Two on PayPal and one via Stripe. 

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/103236544-0225fd00-48fa-11eb-8f4f-978ec7fe3589.png)

**Comment by its-nate** [comment]
Stripe form is back as a hotfix, working on implementing PayPal still, changes coming today.
