### ISSUE TITLE
Newsletter Sign Up

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#198]
Would like to add a newsletter sign up on the home page. 

Should be just under the Instagram section and right above the quote on the home page. 

Here is the design:

https://www.figma.com/file/ZWRwmbNbrr2WmauBhdccru/Spicy-Green-Book-Newsletter?node-id=0%3A1

**Comment by danilobatson** [comment]
Whoever chooses to do this let me know so I can give you access to Mailchimp. 


Not sure if I am doing this completely right to embed what Mailchimp provides in our design but this is the code they gave me. I'm sure it will have to be altered.  


<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://spicygreenbook.us10.list-manage.com/subscribe/post?u=51c52bc37485392a66fae588d&amp;id=e09a86d809" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">Full Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_51c52bc37485392a66fae588d_e09a86d809" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by gkemp94** [comment]
Will also take this one! :)

**Comment by danilobatson** [comment]
@gkemp94 any updates on this?

**Comment by gkemp94** [comment]
@danilobatson Yep, still in the works, got side tracked with Client work this week. Will have availability this weekend to complete.

**Comment by danilobatson** [comment]
@gkemp94 great. Thank you

**Comment by pleaseshutup** [comment]
This looks done. Closing.
