### ISSUE TITLE
Home Page Shop 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#199]
Would like to highlight our shop on the homepage. I think this should go right under the map. 

Here is the design

https://www.figma.com/file/n0a7wZFrZzoXTZKBmkCkbe/Spicy-Green-Book-Shop-Section?node-id=0%3A1

**Comment by pleaseshutup** [comment]
I think this is a duplicate task.

**Comment by danilobatson** [comment]
Whoops
