### ISSUE TITLE
MailChimp

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#200]
Need to connect our domain to MailChimp. See screenshot. What needs to be copied is pasted below pic 

![image](https://user-images.githubusercontent.com/69876068/103388899-65fa2280-4ac0-11eb-880d-251af9bfb5c1.png)

us10-434dc55d-51c52bc37485392a66fae588d.pages.mailchi.mp

148.105.251.17

**Comment by pleaseshutup** [comment]
This is instructions to make mailchimp the host for www.spicygreenbook.org and spicygreenbook.org and we do not want to do this.
