### ISSUE TITLE
Merchandise Home Page 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#202]
Would like to put this on our home page. Should go right under the map. See design here: 

https://www.figma.com/file/n0a7wZFrZzoXTZKBmkCkbe/Spicy-Green-Book---Shop-Section?node-id=0%3A1

**Comment by danielpquinn** [comment]
I will pick up this task

**Comment by pleaseshutup** [comment]
FYI the link to the store is now https://shop.spicygreenbook.org

**Comment by danielpquinn** [comment]
Implemented by PR #216
