### ISSUE TITLE
Navigation Dropdown 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#204]
**Describe the bug**
The about section in nav does not show the drop down arrow on the home page. See screenshot

**To Reproduce**
1. Go to spicygreenbook.org
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/103424261-fe93af80-4b5f-11eb-83fa-2cb6eb93e17b.png)

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [chrome]

**Comment by mrvncaragay** [comment]
@danilobatson is this still the case on your end? dropdown arrow is showing on my end.

**Comment by danilobatson** [comment]
@mrvncaragay no this has been resolved. Thank you
