### ISSUE TITLE
Feature: Donate Page Redesign 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#21]
![SGB-Donate](https://user-images.githubusercontent.com/69876068/97482703-b95ec180-1913-11eb-8cfd-be689dd16aa8.jpg)

**Comment by pleaseshutup** [comment]
To whomever handles this task:

Right now the content on the donate page before the form is handled by prismic so you won't be able to easily implement the images. You can however take on the task of updating the styles on the contact form itself.

**Comment by its-nate** [comment]
Looks like this has stalled, I'll pick it up!

**Comment by its-nate** [comment]
Just an update that I'm still working on this! I broke my hand a few days back while surfing so things slowed down for me a bit, especially on the typing front haha.

**Comment by pleaseshutup** [comment]
@its-nate hows the hand? Should someone else take up this task?

**Comment by its-nate** [comment]
Hey Dan, so sorry for the delay on this... the hand is on the mend and I'm back at the keyboard! Understand if you want to give it to someone else but I can have something by the end of this weekend, if that timeline's ok. Thanks!

**Comment by pleaseshutup** [comment]
Cool please keep working on it and if you can't finish it just let us know and maybe someone can pick up where you left off.

**Comment by danilobatson** [comment]
@its-nate did you finish this task?
