### ISSUE TITLE
PRIORITY: Shop Products Missing 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#211]
**Describe the bug**
A few items we sell are missing from the Spicy Green Book store. That being the T shirt and the Women's Racerback. Screenshots show the items that are missing. 
**To Reproduce**
1. Go to spicygreenbook.org/shop
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/103451064-14929480-4c74-11eb-9742-0d2e2b17512d.png)
![image](https://user-images.githubusercontent.com/69876068/103451069-207e5680-4c74-11eb-9522-35f1c97114ba.png)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]

**Comment by pleaseshutup** [comment]
Not really something I can fix. I have all the products in via shopify using the criteria of anything over a dollar and anything under a dollar gets added to the "website" list and that list is on spicygreenbook.org/shop  so maybe we should go with plan B which is in another ticket where i suggest we just link to the shopify store and not try to put it on spicygreenbook.org/shop

**Comment by danilobatson** [comment]
@pleaseshutup yes lets go with the alias

**Comment by danilobatson** [comment]
@pleaseshutup it was a new product I added. I think everytime I add a product it has to be redone. If you can show me how, I can do it
