### ISSUE TITLE
SGB Store vs Shopify 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#212]
Our store functions through Shopify. 

On our Shopify site, items are clickable to see multiple images as opposed to our site where you can only see one image per product.

I wanted to see if it was possible to make our clickable to see multiple photos. 

Here is the link to our shopify store so you can see what I mean. 
https://spicy-green-book.myshopify.com/collections/all

vs our store 
https://spicygreenbook.org/shop

**Comment by pleaseshutup** [comment]
Shopify does not give much customization for the "store button" integration to throw products on a different website than the shopify store. if you want all the features shopify offers we shoudl probably link people to the shopify store and not spicygreenbook.org/shop

We could alias shop.spicygreenbook.org to the shopify site if you want it on our own domain and not a myshopify.com domain.

**Comment by danilobatson** [comment]
@pleaseshutup  yes can we alias it?

**Comment by pleaseshutup** [comment]
done. https://shop.spicygreenbook.org
