### ISSUE TITLE
Feature: Contact Page Redesign 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#22]
![SGB-Contact](https://user-images.githubusercontent.com/69876068/97482744-cc719180-1913-11eb-813d-09e39c01ea7a.jpg)

**Comment by pleaseshutup** [comment]
The contact form is controlled by honeybook and cannot be styled by us. I recommend you allow a designer into honeybook to style the forms to be more constant and look good on the site.
