### ISSUE TITLE
Report: Control Your Search Listing 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#221]
Website report states we should add descriptions to our search listings. See image

![image](https://user-images.githubusercontent.com/69876068/103815173-d0a6e300-5017-11eb-8b31-3e2069e7670a.png)

**Comment by pleaseshutup** [comment]
We have the tags and the "meta description" box in prismic for all content pages and the home page.

If there is a page where you can't configure this make an issue for it to be statically defined in the code and please provide the actual text you want in there.

You may wish to consult with someone that understands meta descriptions for what to put in each page for the the optimal results with google.

![image](https://user-images.githubusercontent.com/1402663/103815512-4f038500-5018-11eb-81e3-d219987b97e7.png)
