### ISSUE TITLE
Report: Voice Search

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#222]
Website report states we can make improvements for voice search. See image

![image](https://user-images.githubusercontent.com/69876068/103815256-eddbb180-5017-11eb-9f9e-9b22595a0c2a.png)

**Comment by pleaseshutup** [comment]
Is anyone familiar with this?

Seems like the only thing we can do is include the proper meta tags / attributes to provide some hinting to the data on each listing?

They could at least include some documentation on how to resolve this error? I am not entirely sure that this is even something we need to focus on. If someone drops by and see's this issue that has some familiarly with this please chime in. Even if to just provide some insight as to how to address this.

**Comment by danilobatson** [comment]
Closing this until someone prompts this enhancement that has some voice search experience
