### ISSUE TITLE
Report: Vitals

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#223]
Website report states we can make improvements for our vitals. See image

![image](https://user-images.githubusercontent.com/69876068/103815322-0ba91680-5018-11eb-8c34-888ea234648b.png)

**Comment by pleaseshutup** [comment]
When we score good on the Google PageSpeed score this will also be resolved. Going to close this issue as it is a duplicate. We'll keep the pagespeed score issue open until resolved.
