### ISSUE TITLE
Browse Sorting Feature 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#226]
Would like to implement a sorting feature when viewing our listings. 

Here is the design: https://xd.adobe.com/view/4816ff3f-bdb1-4955-b1ad-ddac4bbf62d5-1d45/

**Comment by C-Garza** [comment]
Hello, I saw this issue and would like to work on it. I actually have been and pretty much got it done, but it's actually gotten pretty late 😅, so I'll finish it up and make a pull request tomorrow.

**Comment by danilobatson** [comment]
@C-Garza great. Thank you so much
