### ISSUE TITLE
Shop Redirect: Mobile Site 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#228]
**Describe the bug**
Link to Store in the menu on mobile page takes you to the wrong stie. 

**To Reproduce**
1. Go to 'spicygreenbook.org'
2. Click on 'Store' in nav
3. See error

**Expected behavior**
It should open up a new tab to go to http://shop.spicygreenbook.org

**Smartphone (please complete the following information):**
 - Device: [iPhone11]
 - OS: [iOS]
 - Browser [e.g. chrome]

**Comment by JeroenGoddijn** [comment]
@danilobatson It's seems to be not just the Store. 
When I test it, every link you click in Footer takes you to the destination of the navigation-item below it. 
For example: 

- **About** takes me to **Add Listing**
- **Add Listing** takes me to **Donate**
- **Donate** takes me to **Store**
- **Store** takes me to **Volunteer**
- **Volunteer** takes me to **Press Kit**

**Comment by danilobatson** [comment]
@JeroenGoddijn Can you either pick up that task or make a GitHub issue?

**Comment by C-Garza** [comment]
It looks like the bug is because of a padding issue when the screen is resized below 980. I can fix this.
