### ISSUE TITLE
Home Page Order 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#229]
Can we switch the order and put the "Become A" section above the "Testimonial" Section?

Picture shows current order to be changed

![image](https://user-images.githubusercontent.com/69876068/104493476-f1c48200-5589-11eb-89e0-bbb287f087ae.png)

**Comment by JeroenGoddijn** [comment]
This is already the case on homepage.
Did someone forget to close this issue?

However, as a result the 2 green elements Store and Testimonials are now on top of each other and blended into 1 large green element, which (imho) breaks the design of alternating colors and does not look good/pretty/clean...

**Comment by danilobatson** [comment]
@JeroenGoddijn Yes I screenshotted the error. This needs to be changed to break up the green on green in the current design. This task is agreeing with the sentiment you stated. I would like to me the testimonial section down one to break up the green element

**Comment by JeroenGoddijn** [comment]
@danilobatson I think you might be contradicting yourself then with the request above.

You state that you want "Become a ..." to be positioned BELOW the Testimonials section. But that's already the case on live website. 

Please update the issue definition if you want "Become a ..." positioned ABOVE the testimonials section.
However, keep in mind that you've also requested to put the ABC video between the SHOP and TESTIMONIALS sections in [issue 235](https://github.com/spicygreenbook/greenbook-app/issues/235), which should already solve this design issue and add a white background section in between.

**Comment by danilobatson** [comment]
@JeroenGoddijn Yes you are right. My apologies. The "Become A" section should go above the Testimonials section
