### ISSUE TITLE
Feature: About Page Redesign 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#23]
![SGB-About](https://user-images.githubusercontent.com/69876068/97482807-de533480-1913-11eb-9a05-2a26ea93e4c5.jpg)

**Comment by pleaseshutup** [comment]
The content for this page is managed by a content management system. We will not be able to implement this design while also allowing for anyone with permission to edit the content in prismic. The design needs to be revamped to be simpler and consider the CMS constraints.
