### ISSUE TITLE
PRIORITY: Add Listing Page Design 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#233]
Here is the new design for the add listing page 

https://www.figma.com/file/H82MWVCTbpKzLwuVI9axbX/Add-Listing-01?node-id=0%3A1

Here is the embed for the video: <iframe width="476" height="267" src="https://abc7.com/video/embed/?pid=9623765" frameborder="0" allowfullscreen></iframe>

**Comment by pleaseshutup** [comment]
Is this just to do a mobile design or is this the design for mobile and desktop and the developer should just figure out how to make it look right on desktop?

**Comment by danilobatson** [comment]
@pleaseshutup both phone and desktop

**Comment by danilobatson** [comment]
@pleaseshutup the designer has stopped working with SGB

**Comment by pleaseshutup** [comment]
@danilobatson  There needs to be actual content provided. It would take less time to code in the content than it would be to figure out how to split all of the content up in prismic to be editable in order to implement this design. Can you close the issue until all of the content and finalized images are available?

**Comment by danilobatson** [comment]
@pleaseshutup with the original designer not being available do you suggest the copy is placed right here in the GitHub?

**Comment by pleaseshutup** [comment]
@danilobatson yes that's fine

**Comment by danilobatson** [comment]
@pleaseshutup got it. Closing for now

**Comment by goncahepekiz** [comment]
Hello everyone, I am new to the team and I can help you to edit your Figma file. Can you please tell me, what's the goal? What do we want to change or do?
