### ISSUE TITLE
ABC Video Home Page 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#235]
Can we embed this video right above the testimonial section on the home page

<iframe width="476" height="267" src="https://abc7.com/video/embed/?pid=9623765" frameborder="0" allowfullscreen></iframe>

**Comment by mamta31** [comment]
I will work on this.

**Comment by JeroenGoddijn** [comment]
@mamta31 Please make sure you use a white background for this section. That way we resolve the broken design issue of the 2 connecting green background sections at the same time and this video will visually separate the green SHOP and TESTIMONIALS sections.

**Comment by mamta31** [comment]
Thank you @JeroenGoddijn. I have started working on this and will use white background.

**Comment by JeroenGoddijn** [comment]
@pleaseshutup Can you take a look at this issue? It is open with an outstanding (but conflicting) PR, yet we already seem to have the video implemented on the Home Page... 

Not sure if you just want to close this issue and the corresponding PR? Or unlink the current PR from this issue and link the PR that actually got deployed with this enhandement, before closing it??

**Comment by pleaseshutup** [comment]
I accepted the PR it's ok
