### ISSUE TITLE
ABC Video About Us

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#236]
Can we embed this video on the bottom of the About Us Page

<iframe width="476" height="267" src="https://abc7.com/video/embed/?pid=9623765" frameborder="0" allowfullscreen></iframe>

Additionally can we put a button that is hyperlinked to scroll to the video on this page? The button should be placed right under the first section of copy. 

The button should look like the "Subscribe" button in the screenshot below and read "See Us On ABC"

**Comment by phil4lif** [comment]
@danilobatson Is this just for the web version so in pages/about.js   or do you want the video in Screens/About.js as well?

**Comment by danilobatson** [comment]
I am not sure I understand your question

**Comment by phil4lif** [comment]
After looking at the code more closely I realized the question did not make sense.
