### ISSUE TITLE
Press Kit Button 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#238]
Would like a button to download our press kit. Should look like the "Subscribe" button in the image below and should read "See Our Press Kit"

![image](https://user-images.githubusercontent.com/69876068/104645533-02492b00-5664-11eb-884f-f354af6bd854.png)

![image](https://user-images.githubusercontent.com/69876068/104645517-fd847700-5663-11eb-81db-e04aa66bd09f.png)

**Comment by JeroenGoddijn** [comment]
@danilobatson Where do you want this button exactly? 

Are you referring to:

- replacing the "View our Press Kit" link with a "See our Press Kit" button on the Press page?
- replacing the "Press Kit" link in the Footer with a "See our Press Kit" button
- add the "See our Press Kit" button in the top navigation?
- somewhere else?

**Comment by danilobatson** [comment]
I am referring to your first point. 

replacing the "View our Press Kit" link with a "See our Press Kit" button on the Press page?

**Comment by JeroenGoddijn** [comment]
OK. If someone can assign this issue to me, then I'll fix this when I'm done with Volunteers page. Should be later today.

Using these smaller issues to get used to your codebase.

**Comment by JeroenGoddijn** [comment]
@danilobatson When we deploy the fix, someone needs to remove the "View our Press Kit" link from the CMS. Otherwise, visitors will see the text link first and the green button right underneath it. I added a screenshot of the new version

![localhost_3000_press (1)](https://user-images.githubusercontent.com/48567344/104798084-539f0a80-5789-11eb-87a7-27d47e553ea7.png)

**Comment by JeroenGoddijn** [comment]
Created pull request and described required manual action during deployment.

Would be great if someone can give me rights to link Pull Requests and Assign Issues to myself. ;)

**Comment by danilobatson** [comment]
@JeroenGoddijn I will take it off once it is deployed. I don't see it up yet
