### ISSUE TITLE
Home Page Nav

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#24]
Can we change "Join" to "Add Request" 

Maybe in two line format?

**Comment by pleaseshutup** [comment]
For this i recommend a designer approve. I changed it to "Add Request"  (maybe you meant add listing?)

two lines seems like a bad idea to me.

**Comment by danilobatson** [comment]
I can't think of another word for join. that says add listing. Join is terrible to me and no one business owner who's first time it is at our website will know what that means
