### ISSUE TITLE
Additional Page

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#247]
Still working on the title of this page but this is a combo of the updates page that currently exist but also a page where users can download social media graphics so they can post and show their support. 

Here is the design 
https://www.figma.com/file/3wdEnfmrSm04o70Y4mcR5T/Spicy-Green-Book?node-id=0%3A1

**Comment by pleaseshutup** [comment]
A lot of the code kinda operates on the title/url so let us know when you have that figured out first.
