### ISSUE TITLE
Incorrect label menu-item on mobile web

### ISSUE THREAD

**Issue by JeroenGoddijn** [spicygreenbook/greenbook-app#253]
If you visit the website on your phone,  you will see the menu in the image below.

The label/text of item "Add request" should be replaced with "Add Listing", but the href/link is correct. 

![Screenshot_20210119-230157_Samsung Internet](https://user-images.githubusercontent.com/48567344/105131572-cfad9100-5aae-11eb-9ed2-65b4de96a3c4.jpg)

**Comment by phil4lif** [comment]
Working on this.

**Comment by phil4lif** [comment]
This issue is fixed with PR #257
