### ISSUE TITLE
Social Media & SGB Updates Page

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#254]
Would like to add this page on the site. This will take place of the update page

Here is the design
https://www.figma.com/file/3wdEnfmrSm04o70Y4mcR5T/Spicy-Green-Book?node-id=0%3A1

**Comment by pleaseshutup** [comment]
So you want the Updates screen updated with this design. Maybe i had internet issues but the actual graphics in that page don't seem to be provided. The spec/request/graphics all have to be provided for a developer to be able to complete this task.

**Comment by danilobatson** [comment]
@pleaseshutup correct. And there are no graphics aren't in the page because I was hoping that the graphics would be managed through prismic

**Comment by pleaseshutup** [comment]
Ok i've added a new type in prismic you can add "Social Media Graphics"
From there you can create a new type like "Facebook Profile Graphics"
in that you can add multiple images w/descriptions.

Let me know when those are all in here and then the task is ready to be started.

**Comment by danilobatson** [comment]
@pleaseshutup Done :)

**Comment by pleaseshutup** [comment]
@danilobatson 
The FIGMA design implies that you will have a few banners / graphics for each social network

Then in prismic you've uploaded a lot of graphics but we didn't classify (nor even include the option) to classify as to which social network they go to. 

I can't make sense of the provided images in prismic vs the design in how to actually implement this. Please elaborate?
Maybe you just want all the social media graphics created listed at the top of the page and then all of the updates after that?

**Comment by danilobatson** [comment]
Yes what you said in the latter. 

We don't have graphics designed for FB or Twitter so it is better just to list graphics with the title supplied in Prismic and have the Updates after that

**Comment by pleaseshutup** [comment]
done in 476abc67daa5f79e331c9e08c7d0a3d604bcb2a0

**Comment by danilobatson** [comment]
@pleaseshutup still a few things missing on this design. I will make a new issue request

**Comment by danilobatson** [comment]
@pleaseshutup see #308
