### ISSUE TITLE
RFC: Move 'Download our Flyer' button 

### ISSUE THREAD

**Issue by JeroenGoddijn** [spicygreenbook/greenbook-app#255]
From @danilobatson:

I think the download our flyer button should go with the other buttons of “Fill out Form” and “Donate” and be in implemented in that graphic.

Put it as the third one under the donate button line.

Put “Help spread the word about us by downloading and sharing our flyer”

**Comment by JeroenGoddijn** [comment]
@danilobatson Do you want this button green or white?

I would suggest a white button, so there's only 1 prominent CTA that is green, being the "Fill out Form" button

**Comment by JeroenGoddijn** [comment]
@danilobatson I went with the white button for now, but can always change that if you want.

Question: is anyone aware that the entire bottom section of addListing page (that image and 3 buttons on the right of that image) is not showing at all in the mobile apps??? 
As a work-around for mobile app, I have reinstated that DownloadFlyer button underneath the 6-step image for mobile apps only, so that app users can at least access flyer.

**Comment by danilobatson** [comment]
@JeroenGoddijn white is good for me
