### ISSUE TITLE
PRIORITY: Broken Photo 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#259]
**Describe the bug**
This feature has been very inconsistent and ongoing. Have reported this bug many times currently. Hope to find a long term solution. The photos on the map don't show up on the directory page for several businesses. 

**To Reproduce**
1. Go to 'spicygreenbook.org'
2. Click on 'directory'
3. Click on one of the icons on the map

**Expected behavior**
A pop up with the photo of the listing should come up. Sometimes this work and sometimes it doesn't. Depends on which one you click.  

**Screenshots**

Incorrect 

![image](https://user-images.githubusercontent.com/69876068/105261015-bacf0d00-5b43-11eb-989f-94c9d2b7dedf.png)

Correct 

![image](https://user-images.githubusercontent.com/69876068/105261080-d20dfa80-5b43-11eb-9fe1-05a7ce05a0ff.png)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]

**Comment by JeroenGoddijn** [comment]
I can't reproduce this issue in Chrome (but I don't run iOS).
Someone with an iPhone should reproduce and fix this issue.

**Comment by gabrielhicks** [comment]
I also have not been able to reproduce this issue with Mac OS X on Safari or Chrome.

**Comment by pleaseshutup** [comment]
I recall this being brought up by Danilo a few times and each time have not been able to replicate. My assumption at the time was simply intermittent connectivity to the internet. Only thing that can explain why it works sometimes and does not work sometimes. Would probably need to see his developer tools console in his browser to see if it is some kind of javascript or network error to know where to start looking next to debug.

**Comment by danilobatson** [comment]
No longer able to replicate
