### ISSUE TITLE
Zip Code Search Doesn't Narrow Entries

### ISSUE THREAD

**Issue by anneocraig** [spicygreenbook/greenbook-app#26]
Zip Code Search shows all entries across the country. Using Chrome for MacBook Air.

![image](https://user-images.githubusercontent.com/73661319/97607555-871e9400-19e7-11eb-82a3-48f8bcfedbb9.png)

**Comment by pleaseshutup** [comment]
Zip code search seems to work great, could you try again?

Can you show me what you get when you use zip code: 92886 ?

**Comment by anneocraig** [comment]
Attached screenshots. My zipcode 11415 narrowed it down as did 92886
[image: Screen Shot 2020-10-29 at 8.14.26 PM.png]
[image: Screen Shot 2020-10-29 at 8.13.30 PM.png]
*__________________*
all over creative
brand&marketing+content
anne o. craig
347-559-2020

**Comment by pleaseshutup** [comment]
Sorry, the screenshots do not attach i suppose when replying via email.

Is this resolved then?

**Comment by anneocraig** [comment]
Yes. Resolved.
*__________________*
all over creative
brand&marketing+content
anne o. craig
347-559-2020
