### ISSUE TITLE
PRIORITY: Testimonials Navigation 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#263]
The testimonials page is not in the navigation. Can we add it?

www.spicygreenbook.org/testimonials

**Comment by pleaseshutup** [comment]
im on this

**Comment by JeroenGoddijn** [comment]
I was just looking into this too. I assume it refers to the app? 
Because on the Web it is in the navigation, just nested under "About".
So, more specifics would help to fix it the right way ;)

**Comment by pleaseshutup** [comment]
This is all done
