### ISSUE TITLE
Copy Edit on the About Us Page

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#265]
We need to edit the copy on the About Us Page. The following showcases the copy: 

**Mission Statement**

Spicy Green Book’s mission is to build substantive relationships and increase social trust between three groups of people, Black small business owners, potential customers of these businesses located in their communities, and volunteers passionate about economic justice, all in order to improve the economic well-being of Black business owners, better integrate racially separated communities, and develop marketable skills in volunteers.

**Products and Services**

Spicy Green Book provides a variety of professional services to Black restauranteurs. These include online marketing and advertising, content creation, photography and videography, and business development education all in an effort to increase their business and achieve our mission. SGB does this by getting to know these business owners, understanding their most pressing needs, and attempting to meet those needs by matching the owners with qualified professional volunteers. 

We are a growing group of volunteers with a passion for sparking and creating change. At Spicy Green Book, we want to not only compile a directory of Black-owned businesses, but establish a space where business owners and loyal patrons can come together to support their local community. Additionally, we create volunteer service opportunities for upcoming professionals, matching them with members of these business owners. We offer all these introductory promotional services all a no cost to the business owner. 

 The support we provide these businesses will:

- Decrease the wealth gap

- Create more job opportunities

- Prevent further injustices

- Implement needed reform

- Ensure marginalized people will receive the representation they deserve

Our growing team helps provide marketing services like photography, videography, graphic design, and other creative services. Our mission is to represent everyone with authentic storytelling so our communities can discover and support Black-owned businesses near them.

**A Peek Back To Look Forward**

From 1936 to 1964, during the Jim Crow era, Black men and women were under the persistent threat of violent hate crimes such as lynchings. To help individuals escape this violence, Victor Green created the Negro Motorist Green Book

This guidebook was a resource during the segregation era that included vital places of refuge, such as  hotels, gas stations, grocery stores, night clubs, restaurants, and “tourist homes,” where homeowners welcomed Black travelers who had nowhere else to go. This valuable piece of history gives us some insight to the racial discrimination that existed, and shows us  the importance and ingenuity of Black entrepreneurship. Today we continue to bring attention to Black innovation and invite you to be a part of it.

**Black Owned Businesses**

Each business has a story, and  at Spicy Green Book we set out to share them. By sharing these stories, we can provide a platform where people of varying backgrounds can peek inside to experience the culture within each business. Through this process, we will begin to humanize the Black community and change the learned perspectives, that  lead to unnecessary violence and ongoing systematic oppression. As we begin to change the mindsets of others in our community, we will see an increase in the value of Black lives and a decrease in violent acts towards the Black community. Here we can create a dialogue that uplifts and supports Black men and women, rather than one that continues to indulge in untrue stereotypes.

**How We Are Making Our Listings Different** 

Spicy Green Book offers a space that allows Black owned businesses nationwide to amplify their voices. We are hand curating content for each business so we can represent everyone authentically, and make sure the listing coincides with the owner's vision. Before publishing our listings, we wait for an owner's approval to ensure everything listed on the business's page is accurate and consistent with their brand. Additionally, we as a nonprofit organization, money donated will be redistributed back into the Black community. Spicy Green Book will also make donations to causes that benefit the black community. Together we can continue the fight against racial inequality.

With an understanding of the broad social issues facing the Black community as described below, and with a lived experience in that community, Danilo Batson founded Spicy Green Book in 2020 to build for positive long-term change in the Black community. Beginning with his social network, Mr. Batson and volunteers created a customer-facing website through which Black-owned businesses in the food and beverage industry could begin to communicate to ongoing and potential customers. The aim was able to create a nonprofit to connect professionals who would volunteer their services to assist the online presence of said Black owned businesses to contribute to economic justice.

**Comment by mamta31** [comment]
I Will work on this one.

**Comment by danilobatson** [comment]
@mamta31 Any updates on this task?

**Comment by mamta31** [comment]
Hi, I have already finished this and committed my changes 2 weeks back.  The changes are already there on the website "https://spicygreenbook.org/about". Let me know, if I am missing something.

**Comment by danilobatson** [comment]
Great, thank you.
