### ISSUE TITLE
join slack, seo, and cross browser

### ISSUE THREAD

**Issue by JeffDegoma** [spicygreenbook/greenbook-app#270]
*** PLEASE READ BEFORE MAKING A FEATURE OR CHANGE REQUEST
Discuss the feature with the #product channel in our slack before creating the issue https://join.slack.com/share/zt-jdggpg0w-2oxQotnStBJ59xDPMXGz~g

Changes may require design direction. Please ensure that any issues created provide clear direction to a developer that can only spare a limited amount of time to look into the project and provide their talent ***

--- 

## Slack 
Can the slack invitation link be updated? I can't seem to join the slack group when clicking on the link above.

## SEO
The app isn't ranking at all on a google search for the keywords: `support black business`. I can assist with keyword research and google analytics.

## Cross browser considerations

It's minor but I noticed extra white space when using the Firefox browser.
>>>
<img width="1432" alt="Screen Shot 2021-01-30 at 9 54 24 AM" src="https://user-images.githubusercontent.com/12701844/106359597-b93edb00-62e1-11eb-8468-18193e405598.png">
<img width="1439" alt="Screen Shot 2021-01-30 at 9 54 41 AM" src="https://user-images.githubusercontent.com/12701844/106359596-b8a64480-62e1-11eb-9197-2b9ed2bd9259.png">
<img width="1436" alt="Screen Shot 2021-01-30 at 9 54 51 AM" src="https://user-images.githubusercontent.com/12701844/106359595-b80dae00-62e1-11eb-9da1-cacee597ddb8.png">
<img width="1438" alt="Screen Shot 2021-01-30 at 9 55 03 AM" src="https://user-images.githubusercontent.com/12701844/106359653-0ae76580-62e2-11eb-8903-e157f75d72aa.png">

**Comment by danilobatson** [comment]
@JeffDegoma what is your email address? I can add you to the slack

**Comment by danilobatson** [comment]
@JeffDegoma Also feel free to jump in on that task

**Comment by JeroenGoddijn** [comment]
FYI...it seems like Slack-invite-links expire after X days AND have a cap of 2000 users using it, so you would basically have to update any Slack-invite-links every 30 days or so....

[https://slack.com/help/articles/201330256-Invite-new-members-to-your-workspace#request-an-invitation](https://slack.com/help/articles/201330256-Invite-new-members-to-your-workspace#request-an-invitation)

**Comment by pleaseshutup** [comment]
We should just link to the slack and say the channel to join that will resolve the issue:
spicy-green-book.slack.com

**Comment by JeffDegoma** [comment]
@danilobatson jhd8610@gmail.com

pr sent. see ya'll on slack.

**Comment by danilobatson** [comment]
@JeffDegoma any updates on this task?

**Comment by JeffDegoma** [comment]
@danilobatson. yup. I'm on slack and the white space issue is no more. We can riff about SEO on slack, so I can close this and open a new issue on SEO when we drill down to specifics.
