### ISSUE TITLE
Merch Graphuc Home Page 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#271]
Need to update the merch section on the home page. 

Here is the design: 
https://www.figma.com/file/gQBa7Llmpd1CrkXqyq0q6u/Merch-page?node-id=0%3A1

**Comment by pleaseshutup** [comment]
FYI the provided design does not allow for a very "responsive" approach. At different widths and heights of screens the cropping of the image becomes hard to manage. It also looks terrible on mobile. If we have images intentionally being cropped off the top or bottom of a content section that is supposed to stack on mobile it doesn't look right. 

A better approach would be a graphic that doesn't get cropped so it can be on the left on larger screens then on top for mobile.

**Comment by danilobatson** [comment]
@pleaseshutup I just forwarded this information to the designer

**Comment by danilobatson** [comment]
@pleaseshutup this has been updated 

https://www.figma.com/file/gQBa7Llmpd1CrkXqyq0q6u/Merch-page?node-id=0%3A1

**Comment by danilobatson** [comment]
I will make a new issue since this is closed
