### ISSUE TITLE
Update Testimonials Page

### ISSUE THREAD

**Issue by pleaseshutup** [spicygreenbook/greenbook-app#273]
The testimonials page is working, however, we would like it updated to match this design:

https://www.figma.com/file/Xd3J4jmrUjFosCb14JGouN/SGB?node-id=127%3A17

I think at around 600-800 pixels (mobile) everything should probably go to one column but I will leave it to the developer to find the best looking solution as the design is desktop only.

Developer note: all of the data that you need for this page is there so this is really a UI update and should be pretty easy for anyone familar with layout/styling in react native.

**Comment by JeffDegoma** [comment]
While tinkering around the figma layout I noticed the logos for the listings (and I can easily export them) but does it make more sense to have the logos be added to and pulled from the prismic api?

if I hit that endpoint --> https://spicygreenbook.cdn.prismic.io/api/v1/documents/search?ref=YB8_ShEAACYActNS&q=[[at(document.type%2C+%22testimonial%22)]]&pageSize=100, (most) images of the owners are there but not their logos.

**Comment by JeffDegoma** [comment]
Here's a work in progress.
---

https://user-images.githubusercontent.com/12701844/107158178-4a532900-6956-11eb-9a8d-52a096cab794.mov

---
But instead of `SEE LISTING >` and `WEBSITE >` I liked the logos via the figma layout.

**Comment by JeffDegoma** [comment]
yikes. i just realized that i commandeered this task without asking. if there are any devs already working on this, hit me up.

**Comment by pleaseshutup** [comment]
@JeffDegoma  Jeff there is already a testimonials page setup with the data coming from prismic. All of the data and images are already there. You are just changing the way the cards are presented. If a person is missing their profile picture it is because they didn't provide one and we'd have to render their card without an image.

This task is all yours to finish up. Just wanted to make sure you realize that all the data is ready to go for you in the code already you just need to change the layout. It seemed from your comments that you were statically coding all the people and text in and exported things from figma which shouldn't be needed.

**Comment by JeffDegoma** [comment]
@pleaseshutup Thanks for following up. Apologies if I wasn't clear. I'm definitely NOT statically coding anything except the `People are taking notice` headline.  All the people and text *are* being rendered from the data.  My question, as per the desired figma layout, was to find out if the logos should also be included in the data so it can be rendered. Do you still want the Testimonials Page to have logos for each listing?

SCREENSHOT FROM THE FIGMA LAYOUT:
<img width="843" alt="Screen Shot 2021-02-08 at 8 43 04 PM" src="https://user-images.githubusercontent.com/12701844/107306012-0c3b2f80-6a52-11eb-8a55-3dd3564643d3.png">

**Comment by pleaseshutup** [comment]
@JeffDegoma OH i see it now! My bad in misunderstanding. I think you should bring it up in the #product channel in slack and determine if they want to manage another image with each testimonial in prismic for a logo or omit that in the implementation of the design. IF they do, we need to get that additional image added to the testimonial template and then someone needs to upload logos. It definitely should be managed in the CMS not statically.

**Comment by JeffDegoma** [comment]
@pleaseshutup Not a worry. I totally agree with the logos being managed in the CMS. I was at a crossroads with what to do next but fortunately, rendering the UI is pretty straightforward.

@danilobatson my email is jhd8610@gmail.com. I don't have access to the slack workspace.  Once the #product channel makes a decision to either keep or omit the logos on the updated Testimonials page, the turnaround time should be a day or so and I can get a pull request ASAP. 

Thanks team.

**Comment by danilobatson** [comment]
@JeffDegoma Thank you so much for picking up on this. This task is a priority. I invited you to the slack

**Comment by pleaseshutup** [comment]
@JeffDegoma this seems like it was done can you let us know?

**Comment by pleaseshutup** [comment]
https://spicygreenbook.org/testimonials

seems done to me. closing
@danilobatson just open a new issue if we need tweaks to this page.
