### ISSUE TITLE
Developer Onboarding Tutorial

### ISSUE THREAD

**Issue by pleaseshutup** [spicygreenbook/greenbook-app#278]
It would be very helpful for any new developers to have a start-to-finish tutorial on contributing code to this project. Assume they are beginners with no experience. The tutorial would walk them through step by step how to:

1. Fork the repo and get their development environment setup
2. Make a change to the code
3. Test and see that change on a mobile device through expo, and mobile/desktop web
4. Make a real PR that we accept. The change can just be adding whitespace or something trivial that won't impact things negatively.
5. Keep their repo updated so they can find an issue and try again.

I think this would be best as an annotated screen recording. 

***BONUS POINTS*** 
Separately, if any developer can screen record taking on an real issue and making a PR those videos would also be really helpful.

**Comment by C-Garza** [comment]
@pleaseshutup I'm thinking about doing this for #282. Would I have to record audio as well or just annotate the screen? I don't mind doing either.

**Comment by pleaseshutup** [comment]
Ok I'll take whatever you will give.

You could always upgrade it later when inspired or time permits

**Comment by C-Garza** [comment]
I'm just updating to say I  should hopefully finish up the tutorial in the next day or two.

**Comment by C-Garza** [comment]
@pleaseshutup Sorry for the long delay, some things came up. But I've made a screen recorded video with audio going through the steps for resolving #282. I also have an alternative PDF (and word) document going through all the steps for contributing to this repo. How can I share them with you so you can review them?

**Comment by pleaseshutup** [comment]
You can send them to me dan@spicygreenbook.com

**Comment by pleaseshutup** [comment]
This is done, really great work @C-Garza
