### ISSUE TITLE
Sponsor Page: High Priority 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#281]
Would like to implement this page. Here is the design: 

https://quiet-bird-3981.animaapp.io/

**Comment by Adoni0** [comment]
I can work on this

**Comment by heyitsbuse** [comment]
Hi @Adoni0 ! This is my first time handing off a design to a developer, so please let me know if this prototype is sufficient or if you need any more information. Thanks!

**Comment by Adoni0** [comment]
Looks good! I don't have have any questions as of now, but if any come up I will let you know.

**Comment by pleaseshutup** [comment]
@Adoni0 how's it going?

**Comment by Adoni0** [comment]
Still have a few more styling issues to work out, but I should have it done in the next week.

**Comment by pleaseshutup** [comment]
@Adoni0 was able to commit a PR and merge into the sponsors branch.

I think the final isue was getting things to scroll down the page on native apps (works fine on web)
And this same issue needs to get fixed on #172

**Comment by pleaseshutup** [comment]
This is deployed, the scrollTo function is messed up in expo. Not sure whats up but frankly it is not needed in the mobile app, sponsors page totally works in the app just doesn't have the jump-to buttons. Realistically our sponsors will visit us on the website using work computers and not a personal mobile device IMO.

Lets call this closed.

Thanks again @Adoni0 for your work on this.
