### ISSUE TITLE
Video Thumbnail 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#283]
I would like the following to be the image over our ABC video at the bottom half of the home page. 

![image](https://user-images.githubusercontent.com/69876068/108603857-21bc2d80-735f-11eb-9ab9-9da8282e84d9.png)

**Comment by domferris** [comment]
@danilobatson @pleaseshutup on it

**Comment by pleaseshutup** [comment]
@domferris looks like you're done?

**Comment by pleaseshutup** [comment]
@domferris thanks for your work on this but in order to fix some google page speed issues i had to get this implemented and couldn't wait on you.

Closing.
