### ISSUE TITLE
About Page Text

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#289]
**Describe the bug**
The text is not live. None of the text on this page can be highlighted to be copied. 

**To Reproduce**
1. Go to spicygreenbook.org/about
2. Highlight text
3. See error

**Expected behavior**
I would like to be able to copy and paste text. 

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [chrome]

**Comment by pleaseshutup** [comment]
fix deploying
