### ISSUE TITLE
Small Video In Listing 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#290]
Currently if you go under someone's listing and there is video content it is hard to see. When you click play it plays in a small box that is hard to see unless you go full screen. 

I believe that instead of playing there it should open up a new tab to play the video on our YouTube channel. 

See the screenshot below. Let me know if this needs clarification. 

<img width="1440" alt="Screen Shot 2021-03-05 at 11 57 44 AM" src="https://user-images.githubusercontent.com/69876068/110167232-55a94100-7daa-11eb-97ec-7bbb8b53c229.png">

**Comment by pleaseshutup** [comment]
i will fix

**Comment by pleaseshutup** [comment]
fixed in 3856c33e10091db2fc99965258bbcc7e523e70ad
