### ISSUE TITLE
Share Feature 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#292]
When you go under a listing there should be a way to share the listing. 

Currently on the app there is no way to do this. 

There should be a way to share via text, FB, email, IG, Twitter, Linkkedn, Pinterest, Reddit, copy link, and whatever else is out there. 

Image displays the current view on the app that shows no way to share it to another. The following photos show an example of the share feature on YouTube I believe we should follow. 

![IMG_B437054F2A59-1](https://user-images.githubusercontent.com/69876068/110168009-6c03cc80-7dab-11eb-89e9-5cd7b831738f.jpeg)

<img width="1440" alt="Screen Shot 2021-03-05 at 12 04 03 PM" src="https://user-images.githubusercontent.com/69876068/110168112-9190d600-7dab-11eb-8d70-bb9962cfc25f.png">

<img width="1440" alt="Screen Shot 2021-03-05 at 12 05 56 PM" src="https://user-images.githubusercontent.com/69876068/110168131-981f4d80-7dab-11eb-87fa-94e4adec6535.png">

**Comment by montrell12** [comment]
I'll take care of it

**Comment by montrell12** [comment]
Testing it , do you have any specific icon or design you want me to use or do you want me create it myself?

**Comment by pleaseshutup** [comment]
@montrell12 probably just use the same social icons we use in the footer

**Comment by pleaseshutup** [comment]
@montrell12 hows it going?

**Comment by montrell12** [comment]
Will be done by Saturday

**Comment by pleaseshutup** [comment]
hi @montrell12 thanks for working on this! can you do a PR to get us these changes? 

If you don't think you can complete the work, you could possibly do a PR in a separate branch so someone can finalize it?

**Comment by JeroenGoddijn** [comment]
🤔 🤷🏽‍♂️

**Comment by JeroenGoddijn** [comment]
@pleaseshutup Shall we just reopen this issue as well? Developer went dark on this one too

**Comment by pleaseshutup** [comment]
@JeroenGoddijn yes!

**Comment by orsolyalukacs** [comment]
I can start working on this one.

**Comment by danilobatson** [comment]
@orsolyalukacs Thank you!

**Comment by orsolyalukacs** [comment]
@danilobatson Two ideas for the share button: which one do you prefer?
![share_1](https://user-images.githubusercontent.com/25482492/119436686-43241100-bce2-11eb-9f75-cdf987ad44d8.jpg)
![share_2](https://user-images.githubusercontent.com/25482492/119436690-46b79800-bce2-11eb-96cb-7513d9cb0d99.jpg)
