### ISSUE TITLE
SGB App Back From Listing 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#294]
**Describe the bug**
There is nothing that shows the user how to go back from looking at a listing and return to the search 

**To Reproduce**
1. Go to SGB app
2. Go to any listing
3. See error

**Expected behavior**
User should have a way to go back to search directory 

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/110606983-98b73b80-813f-11eb-912e-051fe73ae62e.png)

**Smartphone (please complete the following information):**
 - Device: [iPhone11]
 - Browser [SGB App]

**Comment by codecustard** [comment]
I'd be happy to work on this issue!

**Comment by mrvncaragay** [comment]
@codecustard I've implemented a basic back button here 0e97ff8de9a79719f1c1a8cd0cbae53381b360b8 . Please create a PR if you manage to implement this feature. For now ill close this issue. thanks!
