### ISSUE TITLE
URGENT: Video Home Page

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#298]
**Describe the bug**
Video on home page does not play 

**To Reproduce**
1. Go to 'spicygreenbook.org'
2. Click on play 
3. see error

**Expected behavior**
Video should play 

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome

**Comment by pleaseshutup** [comment]
fixed in 592c1ff
