### ISSUE TITLE
[Medium Priority] Object instead of text when browsing listings with map

### ISSUE THREAD

**Issue by CeeWho** [spicygreenbook/greenbook-app#3]
Problem exists on Google Chrome v86.0.4240.111

Text [Object, Object] appears instead of text or something else when selecting a listing from the map on the browsing page.
![SGB object text issue](https://user-images.githubusercontent.com/12802568/97192491-538d0100-177e-11eb-98d1-c83543972f0d.png)

**Comment by pleaseshutup** [comment]
fixed in 02608610c2fdeb51513cf621fc075746e45affd9
