### ISSUE TITLE
SGB App Merch Promo

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#300]
**Describe the bug**
The merchandise graphic merchandise is off. Hard to see the clothes. 

**To Reproduce**
1. Go to SGB app
2. Scroll down
3. See error

**Expected behavior**
Refer to how it looks on desktop

**Screenshots**

![E8F5D53F-E0E3-44BE-AF59-FFD5ECA671D5](https://user-images.githubusercontent.com/69876068/110880103-ef815a00-8292-11eb-84da-d2559d32ab35.png)

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - Browser SGB app

**Comment by pleaseshutup** [comment]
@danilobatson Could you like me to the figma files that show how this is supposed to look on desktop and mobile?

**Comment by danilobatson** [comment]
@pleaseshutup https://www.figma.com/file/gQBa7Llmpd1CrkXqyq0q6u/Merch-page?node-id=0%3A1
