### ISSUE TITLE
SGB App New listing

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#301]
**Describe the bug**
The photos aren’t showing on the new listing portion  on the page

**To Reproduce**
1. Go to SGB app
2. Scroll down
3. See error

**Screenshots**

![D0A0DE21-5046-4565-9424-70BD959A701A](https://user-images.githubusercontent.com/69876068/110880574-b3022e00-8293-11eb-990a-30403d938db8.png)

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - Browser SGB app

**Comment by pleaseshutup** [comment]
i'll fix this

**Comment by pleaseshutup** [comment]
i fixed this
