### ISSUE TITLE
The location field does not correctly filter search results.

### ISSUE THREAD

**Issue by erindlilly** [spicygreenbook/greenbook-app#31]
<img width="1457" alt="SGB_incorrect_location_search" src="https://user-images.githubusercontent.com/54216878/97638743-94517800-1a13-11eb-89e4-b9601f75510f.png">

**Comment by pleaseshutup** [comment]
Location search works, however, it works for locations that are more realistically close to a person. e.g. searching for a city, state or zip code 

"irvine, ca" gets a user close. Searching only for "California" could be a 10 hour drive depending on where they are at in california.
