### ISSUE TITLE
Header and footer navigation menu text styles don't match.

### ISSUE THREAD

**Issue by erindlilly** [spicygreenbook/greenbook-app#33]
I would suggest increasing both font sizes overall to improve readability and give the user a bigger target to click on. 

<img width="1364" alt="SGB_navigation_bar_styling" src="https://user-images.githubusercontent.com/54216878/97639219-84866380-1a14-11eb-98e3-d94894992c66.png">

**Comment by pleaseshutup** [comment]
This is a great suggestion, however, it is following the provided design. I think this needs to be taken up with Danilo and whomever is the current designer to provide a design if a change is needed.
