### ISSUE TITLE
Home Page Video Thumbnail

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#331]
Can we add this as the thumbnail for the video on the home page

![Thumbnail-01](https://user-images.githubusercontent.com/69876068/112193565-3ccfc680-8bc5-11eb-802b-a97fb285b599.jpg)

**Comment by ktgr** [comment]
I'll handle this issue

**Comment by JeroenGoddijn** [comment]
Nice job, @ktgr 

Looks great.
