### ISSUE TITLE
Remove Live Chat site-wide

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#334]
Would like the live chat feature removed from the site totally. This chat feature should be removed. This includes the Live Chat logo in the footer of the site

**Comment by JeroenGoddijn** [comment]
Commented out the respective script (pasted below for documentation purposes) in ./pages/_document.js that injected the LiveChat functionality into the pages

            <script
            dangerouslySetInnerHTML={{
              __html: `
              window.__lc = window.__lc || {};
              window.__lc.license = 12115266;
              (function() {
                var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
                lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
              })();
           `}} />
