### ISSUE TITLE
Sponsor Page In Kind Logos

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#335]
The logos at in the footer of the site of RE:Store LA and Vercel need to be added to the in kind support section of the sponsor page. 

![image](https://user-images.githubusercontent.com/69876068/112198565-7a831e00-8bca-11eb-936b-d695c3bd2688.png)

**Comment by JeroenGoddijn** [comment]
@danilobatson Is this what you wanted?

https://greenbook-app-git-fork-jeroengoddijn-335sponsorsinkindl-d536e3.vercel.app/sponsors

There are no design specs or designer provided image files for each of the logos, so it's a bit freewheeling with sizes to make them kinda same size

**Comment by danilobatson** [comment]
@JeroenGoddijn sorry about that. I would ask Buse on slack to better advise on specs. I’m no good at that.
