### ISSUE TITLE
Sponsor Page: Fix Header

### ISSUE THREAD

**Issue by heyitsbuse** [spicygreenbook/greenbook-app#336]
_Hi! I'm the Designer who created the Sponsor Page. I'm creating mini issues to cover the most important updates so that the website can better match the prototype: https://quiet-bird-3981.animaapp.io/_

1) This webpage requires a special header where the secondary navigation (green section) is also fixed. See prototype for demo. I understand that on mobile, this will not be achievable. 

2) For the jump links within the secondary navigation, please edit the position at which the page jumps to because you need to account for the header taking up space. Currently, the section titles are getting covered up.

3) Match the height of the black CTA button "Become a Sponsor" in the secondary navigation to the green CTA button "Become a Sponsor" button later down the page so that they both have 60px height.

4) For CTA buttons, currently text is the only clickable area for the mailto link. Change that so that the entire rectangle is clickable.

_Comment on this issue or DM me on slack if you have any questions!_

**Comment by JeroenGoddijn** [comment]
Item 2 has been fixed. Will work on rest tomorrow

**Comment by C-Garza** [comment]
@JeroenGoddijn I also noticed another issue and that is when the web screen size is smaller than 1100px, the `Sponsor Us` navigation link does not appear in the hamburger menu.

**Comment by JeroenGoddijn** [comment]
> @JeroenGoddijn I also noticed another issue and that is when the web screen size is smaller than 1100px, the `Sponsor Us` navigation link does not appear in the hamburger menu.

@C-Garza is that [issue 339](https://github.com/spicygreenbook/greenbook-app/issues/339)???

**Comment by C-Garza** [comment]
Yes that is, I must have just missed seeing that issue when I commented here.

**Comment by JeroenGoddijn** [comment]
No worries. Just making sure we're talking about the same thing

**Comment by JeroenGoddijn** [comment]
@heyitsbuse Please check the fixes [here](https://greenbook-app-git-fork-jeroengoddijn-master-spicygreenbook.vercel.app) and let me know if this works/looks as expected

**Comment by heyitsbuse** [comment]
Hi, only #3 from my list of requests were actioned. Still need to fix #1, #2, and #4. Please look at the prototype for intent.

**Comment by JeroenGoddijn** [comment]
> Hi, only #3 from my list of requests were actioned. Still need to fix #1, #2, and #4. Please look at the prototype for intent.

Not sure where you looked, but for me all items are working now; except for item 1, because that seemed like an informational statement without a specific change request when I read it initially. However, #333 makes it impossible to test item 3 now, as it is temporarily removed.
