### ISSUE TITLE
Sponsors page missing in mobile navigation

### ISSUE THREAD

**Issue by JeroenGoddijn** [spicygreenbook/greenbook-app#339]
If you visit website on mobile device, there is no navigation item for the /sponsors page. 
Please add this item to the mobile navigation

@C-Garza mentioned these specifics:
"when the web screen size is smaller than 1100px, the Sponsor Us navigation link does not appear in the hamburger menu."

**Comment by ktgr** [comment]
I'll handle this issue

**Comment by JeroenGoddijn** [comment]
Should be quick-fix in ./components/Menu.js

Main question will be exactly where in that menu @danilobatson wants this menu-item listed ;)

**Comment by pleaseshutup** [comment]
This is in the native app mobile menu and web mobile menu now.
