### ISSUE TITLE
Searching for "barbeque" gives no results.

### ISSUE THREAD

**Issue by erindlilly** [spicygreenbook/greenbook-app#34]
I tried more synonyms like "fish" vs "seafood" and found no other issues, but there could be more.

<img width="1385" alt="SGB_barbeque_search" src="https://user-images.githubusercontent.com/54216878/97641264-e052eb80-1a18-11eb-858b-ff2cc74f928f.png">

**Comment by pleaseshutup** [comment]
I recommend the solve for this would be to include the keywords you want the listing to show up for in the listing itself. I will let Danillo know this.

Our search is going to be pretty decent but won't be as complex and sophisticated as google by including synonym terms etc.

**Comment by pleaseshutup** [comment]
We added additional search terms to the content management system and I added support for that new field in the front end. All thats left from here is those that update / manage the listings in prismic to also add search terms like barbeque.
