### ISSUE TITLE
Sponsors screen: Make 2nd/sub navigation fixed to top of screen

### ISSUE THREAD

**Issue by JeroenGoddijn** [spicygreenbook/greenbook-app#343]
EXTRACTED FROM ISSUE #336 created by @heyitsbuse

Hi! I'm the Designer who created the Sponsor Page. I'm creating mini issues to cover the most important updates so that the website can better match the prototype: https://quiet-bird-3981.animaapp.io/

    This webpage requires a special header where the secondary navigation (green section) is also fixed. See prototype for demo. I understand that on mobile, this will not be achievable.

Comment on this issue or DM me on slack if you have any questions!

**Comment by C-Garza** [comment]
I can handle this, I think I know what the issue is preventing it from being fixed.

**Comment by JeroenGoddijn** [comment]
> Are you working on this issue as well @JeroenGoddijn? Because I think I know what is preventing the navbar from being fixed. It could be the same reason as in this PR #304. 

No, go ahead @C-Garza 
I've been working on other issues regarding that page.

Keep in mind we're only showing it on desktop, so that might save you some time/work
