### ISSUE TITLE
Navigation Menu Reorder 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#359]
Would like to change the order of our navigation. Process page is being removed. Please see photo below to see new organization. 

![image](https://user-images.githubusercontent.com/69876068/112912129-afe8a980-90ab-11eb-8208-214f6b0fd1a1.png)

_Recommendations are coming from [this audit](https://mail-attachment.googleusercontent.com/attachment/u/0/?ui=2&ik=88abe10e33&attid=0.1&permmsgid=msg-f:1695341501369217423&th=1787101cfa16f18f&view=att&disp=inline&sadnir=1&saddbat=ANGjdJ-0R5HKH8bDqAFNnOI_oTaVKiX4YwoK4Ms2yOAgHBbCZ0KM-pON2waTlIOUwT-OSRlF_6D2t6yPZWjOc2VmezRYJzkOCZeC5TgnbORo6RUw65RfhDH-_7ELm32WlBKc33aa-8aIF8GjE-RdFNBrz88zZb3sxWwTBZKGdCfismuCs5x21QN7AH2BXfh3uxN90p9D9RuaGydRNJH2mezpnfc2c394BO3fh8eivoLMJrEp-5YyfQHMhZNhql-XDqmPp01HURMP1wyxIig--HFkGpyrbHvFd5cwwY2g3TwK89gz_nSytl1DsDh4cVvDyXKrKu-k39m3pcgTIm_aGBdg75Py4clvewTQtgYK5txw1X4JuMFRDtB0SEjEcdeh-uMACOW-WFqsdeSpvDP8Bxxj8PRWa3f-AADHtCZfyBwOamsvy0fZ1r38Cdfa-42BoT95NCqQRNWg0HkQhCsXOsrKyD0PZOTKT5Q3Q1krLAi4z0CV9vAM-Y27_JWjNgbeFlgOIN3LIdoImnkye_MVjdhvq_Z9LYafRmSQISKenXfMwXVQTDEgb4qhLKw-0ohD5rw7hmMXacRWfjPNmCUIMxozaGynLGrorR1wt7ZnoGCDcNfGhn7K-uLvubhBeWVJjW-GOk7TrGgC1pwHIb0HNGU1XIZ5DbdNW2ld9Fs8k9V4mXvnHqfh2kppciWrTSs)_

**Comment by JeroenGoddijn** [comment]
@danilobatson Can you confirm you want to remove the "Sponsor Us" from the main navigation? I don't see it anywhere in this design/request

**Comment by JeroenGoddijn** [comment]
@danilobatson The "Download our App" is also missing in this design! I assume you want to leave that in the top navigation/menu as well?
