### ISSUE TITLE
URGENT: Volunteer Button Missing Text

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#364]
**Describe the bug**
Not sure what happened here but the text that was on the link to the volunteer form is now missing. 

See photo below and notice empty green box

**To Reproduce**
1. Go to spicygreenbook.org/volunteer
2. Scroll down 
3. See error 

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/112945667-70d94900-90e9-11eb-8664-64fc51d5091d.png)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]

**Comment by codecustard** [comment]
https://github.com/spicygreenbook/greenbook-app/blob/0f8dfe98a4a16652a95398b60cc1451e104865f7/screens/Volunteer.js#L184

https://github.com/spicygreenbook/greenbook-app/blob/0f8dfe98a4a16652a95398b60cc1451e104865f7/utils/getStyles.js#L248-L256

Looks like a mixup with the theming... Depending on the context of "button text color" should use: 'button_white_text' or change the color property of "button_green_text".

@JeroenGoddijn

**Comment by C-Garza** [comment]
Yeah, if the colors are changed now then the buttons have to be updated. The homepage has some buttons with the same issue.

**Comment by danilobatson** [comment]
This issues is relevant to issue #365

**Comment by JeroenGoddijn** [comment]
Fix is being deployed at the moment.
