### ISSUE TITLE
Volunteer Page Video 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#375]
Would like to have a video implemented on the volunteer page. The file is too big to upload here. 

Video URL: http://f.io/Yam4A-uG

**Comment by JeroenGoddijn** [comment]
@danilobatson Can you please add more specifics regarding the video?

• location on page to display video?
• autoPlay (yes/no)?
• muted (yes/no)?
• loop video or only play once?
• etcetera 
• etcetera

**Comment by danilobatson** [comment]
@JeroenGoddijn 

• location on page to display video - **right below the scroll to volunteer form button**
• autoPlay - **no**
• muted- **yes**
• loop video or only play once - **play once**

**Comment by pleaseshutup** [comment]
i got this

**Comment by pleaseshutup** [comment]
done
