### ISSUE TITLE
Add Page Video 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#376]
Would like to add this video to the add page on SGB. 

This video should be right above the infographic and under the first paragraph. 

This video should be muted and auto play if possible. 

Please see product channel on slack as the video is too large to host here. Here is the [link to the message. ](https://spicy-green-book.slack.com/files/U015WK8A1FX/F01TKPNAV7G/sgb_business_owners_web.mp4)

Please use this image as thumbnail 
![image](https://user-images.githubusercontent.com/69876068/114139323-bf45cf00-98c3-11eb-9c0f-7eb65112d6ff.png)

**Comment by pleaseshutup** [comment]
i got this

**Comment by pleaseshutup** [comment]
To put this between the text and image would require us to separate out from prismic. If it's not ok how it is now we'll have to do that.
