### ISSUE TITLE
Map on home page 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#38]
Map on home page is not interactive

**Comment by InerkyJad** [comment]
hover and focus events added

**Comment by pleaseshutup** [comment]
please note there is work in progress on this task in branch "map"

**Comment by InerkyJad** [comment]
it's okay you can add your code then I'll do it again, by the way, what way should i add CSS ( for the redesigns ), the inline style will be too long for one line

-  JavaScript Object
- CSS Stylesheet
- CSS Module

**Comment by pleaseshutup** [comment]
Checkout the "map" branch to see how I handled it.

What I typically do:
if it is a repeated style, I put it into getStyles.js 
if it is a one-off style I do it inline

if it is for web only I use a nativeID="whatever" attribute on the <tag /> and then target it with the site.css file in public/site.css

I am not entirely sure on the best practice for CSS in expo/react-native and this method is "good enough" so far.

**Comment by pleaseshutup** [comment]
This is now merged into master.

Final tweaks are in and deployed. 

c787f39aa5259f76d5416cf622ac8eb081b3bbf1
