### ISSUE TITLE
Navigation Change

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#380]
We have completed a mobile site audit. Pain Point 1 

See image below 

![image](https://user-images.githubusercontent.com/69876068/115069657-bdbe6d00-9ea8-11eb-8f70-1a1e1ab79ea5.png)

See entire audit [here](https://prismic-io.s3.amazonaws.com/spicygreenbook/61231769-e7dc-4d34-a18e-389e72912bbb_SGB+Mobile+Site+Audit.pptx.pdf)

**Comment by pleaseshutup** [comment]
i'll do this
