### ISSUE TITLE
Listing Reorganization

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#381]
We have completed a mobile site audit. Pain Point 2

See image below to see how the listings should be reorganized. 

![image](https://user-images.githubusercontent.com/69876068/115070228-843a3180-9ea9-11eb-9ed0-3b954ee8de70.png)

See entire audit [here](https://prismic-io.s3.amazonaws.com/spicygreenbook/61231769-e7dc-4d34-a18e-389e72912bbb_SGB+Mobile+Site+Audit.pptx.pdf)

**Comment by RoseKimball** [comment]
Hi, I can work on this issue.

**Comment by pleaseshutup** [comment]
thanks Rose!

**Comment by danilobatson** [comment]
Closed with commit [5ba73b0f](https://github.com/spicygreenbook/greenbook-app/commit/5ba73b0f8a1466d0daa6eaf5157628e0885566a5)
