### ISSUE TITLE
No Results Found

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#382]
We have completed a mobile site audit. Pain Point 3

See image below
![image](https://user-images.githubusercontent.com/69876068/115070541-eb57e600-9ea9-11eb-9b19-8e391fee386a.png)

See entire audit [here](https://prismic-io.s3.amazonaws.com/spicygreenbook/61231769-e7dc-4d34-a18e-389e72912bbb_SGB+Mobile+Site+Audit.pptx.pdf)

**Comment by lirondco** [comment]
I can work on this one

**Comment by lirondco** [comment]
![image](https://user-images.githubusercontent.com/60845154/116614143-64b1f880-a8ee-11eb-94f7-9f47a8ab58b2.png)

Issue has been fixed.

**Comment by pleaseshutup** [comment]
great work
