### ISSUE TITLE
Misc Pain Points 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#383]
We have completed a mobile site audit. Pain Point 4

![image](https://user-images.githubusercontent.com/69876068/115070822-4d185000-9eaa-11eb-83d9-7a45fea1e117.png)

See entire audit [here](https://prismic-io.s3.amazonaws.com/spicygreenbook/61231769-e7dc-4d34-a18e-389e72912bbb_SGB+Mobile+Site+Audit.pptx.pdf)

**Comment by orsolyalukacs** [comment]
I would be happy to start working on this issue.

**Comment by orsolyalukacs** [comment]
All points have been fixed. This issue can be closed.

**Comment by mrvncaragay** [comment]
> All points have been fixed. This issue can be closed.

Thanks @orsolyalukacs!
