### ISSUE TITLE
About Us Page Copyedit 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#384]
The about page has been copyedited. 

The full document can be found [here ](https://prismic-io.s3.amazonaws.com/spicygreenbook/b9ee4094-1fa8-4916-920a-ae3922d6c962_SGB_AboutUs.docx)

Can we use this document to change the copy on our about us page.

**Comment by domferris** [comment]
This is ready for review

**Comment by domferris** [comment]
@danilobatson This has been completed and merged

**Comment by danilobatson** [comment]
@domferris Great thank you. Can you just adjust the line breaks between sections of the copy? It seems a little too big with all that white space. I can create an issue for this specifically if you would like?

**Comment by domferris** [comment]
You got it @danilobatson. No need to open a separate issue. I'll ping when this is updated

**Comment by domferris** [comment]
@danilobatson this update is now live

**Comment by danilobatson** [comment]
@domferris Great. Thank you.
