### ISSUE TITLE
Content on Home Page below "Visit Our Store" is not loading on iOS 13.3.1

### ISSUE THREAD

**Issue by orsolyalukacs** [spicygreenbook/greenbook-app#387]
**Describe the bug**
Content on Home Page below "Visit Our Store" is not loading on iOS 13.3.1

**To Reproduce**
1. Go to the Home Page
2. Scroll down to 'Visit Our Store'

**Expected behavior**
Rest of the homepage should load.

**Screenshots**
https://user-images.githubusercontent.com/25482492/115462686-90e3c000-a1f0-11eb-8aff-6132aae8b2f4.mp4

**Smartphone:**
 - Device:  iPhone 6s
 - OS: iOS 13.3.1
 - Browser: not applicable 

**Additional context**
I also checked in Expo Go in iPhone 6s and the issue persists. I have reproduced the issue several times.

**Comment by pleaseshutup** [comment]
fixed
