### ISSUE TITLE
About Us Video Dimensions 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#388]
**Describe the bug**
The first video at the top of the about page has the incorrect dimensions. I believe the dimensions should be 1080 × 1080 ??

**To Reproduce**
1. Go to [spicygreenbook.org/about](spicygreenbook.org/about)
2. See error

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [e.g. chrome]

**Comment by pleaseshutup** [comment]
on it
