### ISSUE TITLE
About page photoUpdate 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#395]
Minor updates to the photos on the about page. 

Please see zip file for assets to be changed. There are a few images of the owners and the book on the about page that are updated

[sgb about page - 2021.05.09 - updated images.zip](https://github.com/spicygreenbook/greenbook-app/files/6464267/sgb.about.page.-.2021.05.09.-.updated.images.zip)

**Comment by Darshana343** [comment]
I'm interested to look into this issue!

**Comment by danilobatson** [comment]
All yours @Darshana343

**Comment by danilobatson** [comment]
Issue resolved with commit [1f4dd71](https://github.com/spicygreenbook/greenbook-app/commit/1f4dd71508846cb1b6d3b200038fae273f674198)
