### ISSUE TITLE
Volunteer Page Design Update

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#397]
Hello, 

We are looking to update our volunteer page. Please click the link below to see the figma. 

https://www.figma.com/file/gbYg1TsTg5iGnPjo9K9cKT/Volunteer?node-id=0%3A1

Below is the infographic used 

![signupprocess](https://user-images.githubusercontent.com/69876068/118768499-f0ef7580-b833-11eb-9efa-32eef89d4fb0.jpg)

**Comment by mikayla-bryant** [comment]
I'm interested in working on this issue

**Comment by danilobatson** [comment]
@mikayla-bryant It's all yours

**Comment by orsolyalukacs** [comment]
I will take up this issue.
