### ISSUE TITLE
Volunteer Video Thumbnail

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#398]
Hoping to implement a new thumbnail for the video on top of the volunteer page. Here is the image. 

![Spicy Green Book_Thumbnails_Volunteer - 1920 x 1080](https://user-images.githubusercontent.com/69876068/118768679-23996e00-b834-11eb-9100-22d2082c4a30.jpg)

**Comment by kyoga99** [comment]
@danilobatson I can look into this

**Comment by danilobatson** [comment]
@kyoga99 All yours
