### ISSUE TITLE
[Low Priority] Green box for restaurant name on listing page is too tall

### ISSUE THREAD

**Issue by CeeWho** [spicygreenbook/greenbook-app#4]
Problem found on chrome 86.0.4240.111

The green box that serves as the background for the name of a business on that business's listing page appears to be too tall and extends into the above box.
![SGB Listing GreenboxSize](https://user-images.githubusercontent.com/12802568/97193092-fcd3f700-177e-11eb-87b7-253f4e2bc04f.png)

**Comment by pleaseshutup** [comment]
fixed in ef7c703598a99dd46d3493c5577199682869b467
