### ISSUE TITLE
Front-end Developer Needed: Image Gallery

### ISSUE THREAD

**Issue by pleaseshutup** [spicygreenbook/greenbook-app#40]
Are you an awesome front-end designer/developer?

When you go to an individual listing on spicy green book such as https://spicygreenbook.com/biz/urban-burger and tap on one of the photos it opens the <ImageGallery /> component. We'd love for someone to make that experience of browsing the photos of an individual listing to be an awesome experience. Some listings such as https://spicygreenbook.com/biz/pineapple-express-trap-kitchen also have an available video that you may also wish to include.

If you wish to take on this task, please let us know. Be sure to test on ios/android and all web browser screen sizes.

**Comment by pleaseshutup** [comment]
We currently have a volunteer that has accepted this task. Thanks @Arax1

**Comment by mrvncaragay** [comment]
@Arax1 i think it is safe to close this?

**Comment by Arax1** [comment]
I think so too, until more improvements are needed in the future.
