### ISSUE TITLE
Donate Page Update 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#405]
Please see photo below to see the updated donate page. The pdf below has some specs to fulfill this request.

![sgb-donation-v1](https://user-images.githubusercontent.com/69876068/120261136-1fb21680-c24c-11eb-89f9-32dd6c7a619c.png)

[SGB - Donate Page - CSS Specs to Dev.pdf](https://github.com/spicygreenbook/greenbook-app/files/6573086/SGB.-.Donate.Page.-.CSS.Specs.to.Dev.pdf)

**Comment by mrvncaragay** [comment]
@danilobatson are we removing this part or just leave it?
![Screen Shot 2021-06-01 at 2 22 56 PM](https://user-images.githubusercontent.com/1195427/120392152-eda0c300-c2e4-11eb-93a8-74647117459c.png)

**Comment by danilobatson** [comment]
@mrvncaragay Sorry, good catch. Please leave the form

**Comment by mrvncaragay** [comment]
> @mrvncaragay Sorry, good catch. Please leave the form

great, ill update the donate page.

**Comment by mrvncaragay** [comment]
updated 074cc7b1814ce4aca3b7daa37779b3152cd94255
