### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#41]
Seems like looking on the desktop that it would be easier to navigate and digest if we could zoom out a little bit. 

The photos and imagery are so bag that it takes over the whole screen and can't see the borders that I find myself zooming out to 75%. Would like to take it out some.

**Comment by pleaseshutup** [comment]
I'm not sure what this means, i'm gonna need a visual to implement it. This may require a designer. Unless you want the header to be a little shorter and the "Support black-owned" text to be smaller??
