### ISSUE TITLE
CVC cell wants me to input a ZIP code instead. I've tried twice.

### ISSUE THREAD

**Issue by DebVM** [spicygreenbook/greenbook-app#413]
**Describe the bug**
I'd like to make a donation on the website but when I get to the CVC cell, the system wants me to put in a ZIP code. Also, for the billing address section there is only a street address and zip code cell showing. Perhaps you are aware of that but it seems odd to not input the state. 

**To Reproduce**
1. Go to '...' https://spicygreenbook.org/donate
2. Click on '....'input credit card details
4. See error CVC wants a ZIP

**Expected behavior**
A clear and concise description of what you expected to happen. My expectation is to see a successful donation has been processed and confirmed.

**Screenshots**

![image](https://user-images.githubusercontent.com/70344441/122437940-2f2da100-cf68-11eb-8bde-24636981d087.png)
sorry, I tried to copy and paste the screenshot but this code is the only thing showing up. I hope you can see it.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] latest and greatest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JeroenGoddijn** [comment]
@pleaseshutup besides the UX description regarding the non-existent STATE field, I believe this is a non-issue as described. 

The CVC and ZIP are 2 separate fields and each placeholder text for their own input field. I do, however, feel that this could have been made more visually clear by visually separating the 2 input fields (with i.e. color or border)

**Comment by danilobatson** [comment]
Agreeing with @JeroenGoddijn I believe not having a place for a state is a non-issue as this info may be gathered via zip code with Stripe. 

Closing until this issue reappears if needed.
