### ISSUE TITLE
About - Volunteer Page data not loading on iOS web browser

### ISSUE THREAD

**Issue by orsolyalukacs** [spicygreenbook/greenbook-app#416]
**Describe the bug**
On the About - Volunteer page, only one of the volunteers shows on iOS web browser.

**To Reproduce**
1. Go to 'About.'
2. Click on 'Volunteers'
3. See error: only one of the volunteers is being shown at once.

**Expected behavior**
A list of all the volunteers should be shown.

**Screenshots**
![IMG-6612](https://user-images.githubusercontent.com/25482492/125985180-f677268a-2fa0-42e8-bf8e-5f0dc686381a.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 6S
 - OS: iOS 13.3.1
 - Browser: Chrome and Safari
 - Version Chrome Version 91.0.4472.80, Safari version 13

**Comment by danilobatson** [comment]
@orsolyalukacs I was unable to replicate this issue. I tried both on the app and the mobile web to be sure. I am also using an iPhone. 

Device: iPhone 11 Pro 
OS: iOS 14.6
Browser: Chrome 


Is this issue still present?

**Comment by danilobatson** [comment]
Issue no longer present
