### ISSUE TITLE
Video On Home Page is Missing 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#419]
**Describe the bug**

**To Reproduce**
1. Go to 'www.spicygreenbook.org/'
2. Scroll down on home page to the video thumbnail
3. See error (No where to hit play)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]

**Comment by pleaseshutup** [comment]
Can't replicate, video plays fine.

**Comment by danilobatson** [comment]
Nevermind. i need a new laptop
