### ISSUE TITLE
Search Feature 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#425]
**Describe the bug**
The search feature is not turning up with the results you would expect. 

**To Reproduce**
1. Go to 'spicygreenbook.org'
2. In search bar type in  'All Flavor No Grease' in 'Los Angeles, CA'
3.See error of query rendering wrong results. 

**Expected behavior**
The business of All Flavor No Grease should be the first result in the query. Listed here [https://spicygreenbook.org/biz/all-flavor-no-grease](https://spicygreenbook.org/biz/all-flavor-no-grease)

Note: That the app does not seem to have this problem. Search works fine on the app. 

**Screenshots**
Screen shot shows wrong search results returned 
![Screen Shot 2022-02-08 at 1 01 36 PM](https://user-images.githubusercontent.com/69876068/153075051-353462bd-d0b6-496a-81fa-ab8e8f457095.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome

**Comment by pleaseshutup** [comment]
fixed
