### ISSUE TITLE
Home Page Copy editing 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#43]
Please make the following adjustments: 

"Inspired by Victor Green, Spicy Green Book is a team of volunteers committed to compiling a directory of black owned businesses. Our mission is to establish a space to help people who seek to create change within their communities."

Please add a hyphen to make it: Support Black-Owned Restaurants

On the Home page at the "About Us" section--> "Spicy Green Book **comprises** a team of volunteers...."  is a verb with greater detail that has a more assertive flavor and tone than "Spicy Green book is a team of volunteers...", but that is up to you if you want to make that change to that section.

**Comment by pleaseshutup** [comment]
The inspired by victor green part was already updated per another issue with a higher ID so i assume it was the more recent request.

"Support black-owned" text updated with hyphen.
