### ISSUE TITLE
Mobile page won't open 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#46]
![image](https://user-images.githubusercontent.com/69876068/98178482-9bfc9b00-1eb1-11eb-8815-2180b3d4a42f.png)

**Comment by pleaseshutup** [comment]
How do I replicate this issue?

Does it happen randomly?

Is it only when clicking a link from slack?

**Comment by danilobatson** [comment]
This was submitted by another person in the slack. Forgot who. Will open again if it comes up again.
