### ISSUE TITLE
Mobile Map: Individual Listings 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#47]
Having a map on the individual listing will help a lot for the user. Especially on places that don't have a physical address such as an at home service or food truck. 

It is hard to tell if a business is near you.

**Comment by pleaseshutup** [comment]
Where would this go in relation to the provided design?

**Comment by danilobatson** [comment]
If you are looking on your phone I guess we should put it right above the bio

**Comment by pleaseshutup** [comment]
i'll do this now
