### ISSUE TITLE
Map Images

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#49]
Some of the images are not popping up on the map. 

![image](https://user-images.githubusercontent.com/69876068/98284529-1a127d80-1f56-11eb-91eb-3599f4be4b13.png)

![image](https://user-images.githubusercontent.com/69876068/98284565-28609980-1f56-11eb-9db2-e3f6f82917f7.png)

![image](https://user-images.githubusercontent.com/69876068/98284576-2c8cb700-1f56-11eb-9546-7db745abeb91.png)

**Comment by pleaseshutup** [comment]
can't replicate, assume this must have been temporary/intermittent internet issues. I can see the images fine on all the items.
