### ISSUE TITLE
Instagram Thread

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#5]
Photo thread on home page isn't there

**Comment by pleaseshutup** [comment]
instagram feed on home page works for me, you're still having issues? screenshot or what device/browser?

**Comment by danilobatson** [comment]
Yea still no thread. On my mac using google chrome

![image](https://user-images.githubusercontent.com/69876068/97394845-d9a16880-18a0-11eb-96f4-3b00509752ba.png)
