### ISSUE TITLE
Home Page Copy

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#52]
Under the about us section on the home page the copy needs to be edited as follows:

"Inspired by Victor Green, Spicy Green Book is a team of committed volunteers compiling a directory of Black owned businesses and performing marketing services for these businesses free of charge. We are establishing a space for people who seek to create change, and creating a platform for them to invest in Black business owners in their communities."

**Comment by pleaseshutup** [comment]
fixed in 4b8a89ea5548fffa2dc77303749e17de13e989a7
