### ISSUE TITLE
Urgent: Do Well Brands Gallery Not Opening 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#56]
You can now go to the listing but when you click on one of the pictures you get an error 

![image](https://user-images.githubusercontent.com/69876068/98450297-8cb76080-20f0-11eb-991e-8a26306e8eb4.png)
![image](https://user-images.githubusercontent.com/69876068/98450302-90e37e00-20f0-11eb-81d0-7c7134c8baae.png)

**Comment by pleaseshutup** [comment]
Fixed in code, but also keep an eye out for adding blank items in prismic

![image](https://user-images.githubusercontent.com/1402663/98453270-36581b00-210c-11eb-8348-4162fb822301.png)
