### ISSUE TITLE
.org

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#59]
Can we get spicygreenbook.org and start forwarding it there from spicygreenbook.com

**Comment by pleaseshutup** [comment]
The site is now available on https://spicygreenbook.org/ 

One thing to consider: SEO matters and having a single domain is important. All of the media coverage and existing websites you have right now point to spicygreenbook.com and switching domains *may* have an impact on the site's search ranking. This can be mitigated with a proper sitemap and redirects, however, none of those 3rd party links will likely be updated and the .com and .org distinction may not be that valuable to most of our visitors. 

Having the site available on both domain is not an issue as long as we set a tag in the markup to specify the cannonical url and for that we should settle on the actual domain we want to make the primary. 

I am voting for the .com to be the primary and have the site available on the .org as needed in different literature and cards. But really it's up to you, Danilo. Talk to people and come up with a decision. Marketing people that understand google and that have done tons of research are likely a better resource than I am.
