### ISSUE TITLE
Press Kit

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#61]
Add Press Kit as a downloadable pdf. Attached two versions as one is for mobile. 

[SGB Press Kit.pdf](https://github.com/spicygreenbook/greenbook-app/files/5515474/SGB.Press.Kit.pdf)

[SGB Press Kit Mobile.pdf](https://github.com/spicygreenbook/greenbook-app/files/5515459/SGB.Press.Kit.Mobile.pdf)

**Comment by pleaseshutup** [comment]
Where?

**Comment by danilobatson** [comment]
Adding as downloadable pdf

**Comment by pleaseshutup** [comment]
Yea, I can put a link to these files on the website, where on the website do you want it?
In the footer?
On a particular page?

Do you want a new page created? What do you want to title it? Will it only have these links on it?

Note that the footer design does not really leave much room for extra links, however, I can probably just figure it out.

**Comment by danilobatson** [comment]
Let's go for the footer and on the press page? 

Titled "Press Kit"

I believe the links on it are good as is.
