### ISSUE TITLE
Urgent: App Bug

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#62]
App on iOS is spontaneously closing anytime I hit "browse" or try to use the search function

**Comment by danilobatson** [comment]
This is from an iphone, as opposed to an ipad. Not sure if that matters

**Comment by pleaseshutup** [comment]
You cannot publish listings that are incomplete. If they have certain critical missing data required to render them in the list or the listing it will break the app. Kalypso Ice Box didn't have any images or a primary image set. I have a filter in that tries to filter out incomplete listings now, however, that will take a while to get a new build created and approved by the app store.
