### ISSUE TITLE
Map on Home Page

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#63]
Interactive map that is on the home page should have a way to X out of a pop up after clicking on the state. 

You can't close the window after clicking on the state. Would like to see an X on the upper right corner on the pop up if possible. 

Photo shows current display 

<img width="1344" alt="Screen Shot 2020-11-10 at 8 34 12 AM" src="https://user-images.githubusercontent.com/69876068/98702693-911d8c80-232f-11eb-8851-c4bb6d279c48.png">

**Comment by InerkyJad** [comment]
can we do better? Maybe a tooltip showing on hover ofc that means it closes automatically, and show on focus for the mobile.

**Comment by pleaseshutup** [comment]
@InerkyJad hover events become hard to manage when you need the layer to stay up and click on the links inside. I'll add the X to close and keep it as-is. 

I'd rather avoid too much hover dependent things so there is consistency between the apps.
