### ISSUE TITLE
Tablet Issue (See Image)

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#65]
<img width="653" alt="Screen Shot 2020-11-10 at 8 53 39 AM" src="https://user-images.githubusercontent.com/69876068/98705191-4cdfbb80-2332-11eb-82ed-23a7d84749fc.png">

<img width="273" alt="Screen Shot 2020-11-10 at 8 54 56 AM" src="https://user-images.githubusercontent.com/69876068/98705349-78fb3c80-2332-11eb-89b1-33c3868b428e.png">

**Comment by Jerocam** [comment]
Hello, I think I can fix it. lmk

**Comment by pleaseshutup** [comment]
join our slack if you have questions https://spicy-green-book.slack.com use the #developers channel

**Comment by pleaseshutup** [comment]
This was fixed by @InerkyJad (thanks!!) closing.
