### ISSUE TITLE
Expo / React Native Stack Navigation

### ISSUE THREAD

**Issue by pleaseshutup** [spicygreenbook/greenbook-app#68]
It would be ideal for someone to take a look at the way we handle changing navigation/views for the mobile apps to help support stack navigation in order to get the back/forward etc working in android and ios.

**Comment by mrvncaragay** [comment]
@pleaseshutup I will look into this and see if I can convert the current set up to Stack Navigation.

**Comment by pleaseshutup** [comment]
Awesome!

**Comment by pleaseshutup** [comment]
@mrvncaragay nice work on this. Will close this for now and we will continue to optimize moving forward.
