### ISSUE TITLE
Image Gallery 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#71]
Some of the images in the gallery are not loading and are grayed out. This is apparent on multiple listings. Often it gets stuck and I have to refresh

<img width="1371" alt="Screen Shot 2020-11-10 at 7 50 16 PM" src="https://user-images.githubusercontent.com/69876068/98763080-13d53480-238e-11eb-921f-ecb62cd12a38.png">

**Comment by pleaseshutup** [comment]
This seems like an intermittent network issue. Closing for now, please open again if you can replicate this issue reliably.
