### ISSUE TITLE
Feature: Current Location 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#72]
Hoping someone can include "Current Location" on search bar. The mock up illustrates this below 

![image](https://user-images.githubusercontent.com/69876068/98763246-71698100-238e-11eb-8a55-7179e40aa8b7.png)

**Comment by danielpquinn** [comment]
I'm going to pick up this task.

**Comment by its-nate** [comment]
Hey @danielpquinn! I forgot to comment here but I started working on this a little over the weekend—not too far though. Haven't started routing the lat/lon through the search query yet, which I assume is the bulk of it. I did however spend some time on the visual element of the current location box popping up (hit a snag I haven't worked through yet). Anyway, happy to let you take over as lead on this one as this feature was a bit ambitious for me. If you want me to share what I'd done visually so far and describe the snags I was hitting, happy to do that as well. Maybe you have a solution! Hit me up on slack if you want to chat through it more.

**Comment by danielpquinn** [comment]
Hi @its-nate, I didn't get very far on this one yet either but I do have ideas about how it will work and I'm planning to continue working on it this week.

If you have a branch with your visual changes somewhere that I can check out I would be happy to take a look and possibly borrow ideas from it :)

**Comment by danielpquinn** [comment]
Status update: I have a web version of this working and will submit a PR soon. I'm going to do the native version in a separate PR.
