### ISSUE TITLE
Add box shadow to menu

### ISSUE THREAD

**Issue by cshin1** [spicygreenbook/greenbook-app#73]
Add a box shadow to all menus/dropdowns. This will help differentiate the white background of the menu from the  white background of the webpage. See image:

![image](https://user-images.githubusercontent.com/9870891/98771158-c965af00-23b1-11eb-8248-d44f8a206453.png)

**Comment by danielpquinn** [comment]
I am picking up this task.

**Comment by pleaseshutup** [comment]
thanks @danielpquinn great work
