### ISSUE TITLE
Mobile App: White bar on homepage

### ISSUE THREAD

**Issue by likeawesome** [spicygreenbook/greenbook-app#74]
White bar the top of the homepage, should be filled in with the top header color/background.

![iOS14-2-iPhone11_7629](https://user-images.githubusercontent.com/74067650/98772943-1a22db00-23a5-11eb-90d4-945c59f0c5bb.jpg)

**Comment by danielpquinn** [comment]
I think that maybe @mrvncaragay fixed this issue in his PR: https://github.com/spicygreenbook/greenbook-app/pull/121

**Comment by mrvncaragay** [comment]
not sure if I did, but i dont see this issue anymore on my end.

**Comment by danielpquinn** [comment]
Okay cool, I'm going to go ahead and close this one then. FYI @pleaseshutup
