### ISSUE TITLE
Mobile App: 

### ISSUE THREAD

**Issue by likeawesome** [spicygreenbook/greenbook-app#75]
Hamburger menu icon is not a standard icon. Hamburger icons are generally 3 horizontal lines. 

Severity: 2

1 | Cosmetic problem only
2 | Minor usability problem; fixing this should be given low priority
3 | Major usability problem; important to fix, high priority
4 | Usability catastrophe; must be fixed before product can be released

![iOS14-2-iPhone11_7630](https://user-images.githubusercontent.com/74067650/98773043-57876880-23a5-11eb-85f6-d908ad194f40.jpg)

**Comment by pleaseshutup** [comment]
This has been fixed by @mrvncaragay with his awesome overhaul of the mobile app navigation
