### ISSUE TITLE
Mobile App: Text in search box not vertically centered

### ISSUE THREAD

**Issue by likeawesome** [spicygreenbook/greenbook-app#76]
Text in search box not vertically centered. (I think this issue may have been logged already.)

Severity: 1
1 | Cosmetic problem only
2 | Minor usability problem; fixing this should be given low priority
3 | Major usability problem; important to fix, high priority
4 | Usability catastrophe; must be fixed before product can be released

![iOS14-2-iPhone11_7631](https://user-images.githubusercontent.com/74067650/98773219-b4831e80-23a5-11eb-874c-aed5806dfab8.jpg)

**Comment by its-nate** [comment]
@likeawesome this is a dupe of #77, can be closed.

**Comment by pleaseshutup** [comment]
Looks resolved too. Things look centered on my phone.
