### ISSUE TITLE
Mobile App: New businesses carousel-- add location

### ISSUE THREAD

**Issue by likeawesome** [spicygreenbook/greenbook-app#79]
After the name of the business, there should be a line break followed by the location of the business. Users need to know the location of the restaurant. Location is an important factor in choosing a business to support.

Severity: 2
1 | Cosmetic problem only
2 | Minor usability problem; fixing this should be given low priority
3 | Major usability problem; important to fix, high priority
4 | Usability catastrophe; must be fixed before product can be released

![iOS14-2-iPhone11_7634](https://user-images.githubusercontent.com/74067650/98773452-31ae9380-23a6-11eb-84f5-43a4f64c7a20.jpg)

**Comment by pleaseshutup** [comment]
This is a good idea. You can look at the SGBMap.js component to see how we extract the city/state from the address.

If you take on this task, it would be really awesome for you to move that logic of getting city/state from the address into it's own utlity in utils/getCityState.js so we can reuse it in the map component and on this scroller. Possibly even just set city/state as properties in the row when doing getData({type: 'listing'}).

**Comment by danielpquinn** [comment]
I'm picking up this task.
