### ISSUE TITLE
Press Page

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#8]
Articles are cut off
![image](https://user-images.githubusercontent.com/69876068/97242150-4e48aa00-17b0-11eb-8c0b-9a9de8a92d90.png)

**Comment by pleaseshutup** [comment]
it's just the title and the image provided. how are they cut off? they link to the articles.

**Comment by danilobatson** [comment]
See on the left and right of the article. It is cut off. Makes it hard to see. 

![image](https://user-images.githubusercontent.com/69876068/97394781-ae1e7e00-18a0-11eb-9737-649741db2996.png)

**Comment by pleaseshutup** [comment]
I think the intent here with this is similar to the updates page, an image to go with the title and they click to go see the whole article. Not meant to show them a screenshot of the page to read inline.

This page should probably be a 3 column grid which would make the images too small to read anyway.

**Comment by pleaseshutup** [comment]
press page overhauled per issue #20
