### ISSUE TITLE
Mobile App: Homepage - US and Canadian Map

### ISSUE THREAD

**Issue by likeawesome** [spicygreenbook/greenbook-app#80]
The graphic of the map of the US and part of Canada feels awkward and confusing. The image is not created with consistency. All the continental US states are shown, but only one Candian province is shown. I think this map needs to be redesigned to make it more clear and easier to understand. One idea might be to use text to spell out the states/provinces where you can find SGB businesses. 
 
Severity: 2
1 | Cosmetic problem only
2 | Minor usability problem; fixing this should be given low priority
3 | Major usability problem; important to fix, high priority
4 | Usability catastrophe; must be fixed before product can be released

![iOS14-2-iPhone11_7635](https://user-images.githubusercontent.com/74067650/98773779-e2b52e00-23a6-11eb-8bfc-9d7c87345180.jpg)

**Comment by pleaseshutup** [comment]
We are only using the vector paths from the provided design. This is more of a designer task than a developer task for the website.  If you do find a designer to provide an update, please speak to Arial about getting the source of the file and what it took to get it to us in a proper format.
