### ISSUE TITLE
Mobile App: Homepage -  How Can I Help icons

### ISSUE THREAD

**Issue by likeawesome** [spicygreenbook/greenbook-app#81]
Icons that represent the text information would be helpful here instead of repeating the same arrow. 

![iOS14-2-iPhone11_7637](https://user-images.githubusercontent.com/74067650/98774193-bf3eb300-23a7-11eb-8f8b-0a00e9d3450c.jpg)

**Comment by danilobatson** [comment]
@likeawesome thank you for auditing the site. Do you mind emailing me at d.batson@spicygreenbook.com to discuss

**Comment by pleaseshutup** [comment]
We've removed these per your suggestion as they were unnecessary.
