### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#9]
"Browse" is hard to see on the home page. 

May need to bold the text

**Comment by pleaseshutup** [comment]
Are you talking about in the nav? a screenshot would help

**Comment by danilobatson** [comment]
On the home page. The browse in the nav is hard to see being right over the soup. Maybe we can put it over the black part of the bowl. 

![image](https://user-images.githubusercontent.com/69876068/97393788-6ac40f80-18a0-11eb-8c04-f0816f387565.png)

**Comment by danilobatson** [comment]
A good fix would be...
As you scroll down the home page a black box appears in the nav to keep contrast on the titles. Could have that be there permanently and not only appear when scrolling.

**Comment by pleaseshutup** [comment]
i made adjustments that will help, but it kills the whole point of the design to overlap the image with the nav instead of letting it show through.
