### ISSUE TITLE
Mobile App: Drop down menu "Add request" language 

### ISSUE THREAD

**Issue by likeawesome** [spicygreenbook/greenbook-app#91]
"Add request" is confusing language to new visitors. Can we think of a way of being more explicit? "Add your listing," "Add a listing," "Submit a business," "Add a business" could be better options.

Severity: 2
1 | Cosmetic problem only
2 | Minor usability problem; fixing this should be given low priority
3 | Major usability problem; important to fix, high priority
4 | Usability catastrophe; must be fixed before product can be released

![iOS14-2-iPhone11_7638](https://user-images.githubusercontent.com/74067650/98839537-e24a8080-2402-11eb-8924-34176c5311a0.jpg)

**Comment by pleaseshutup** [comment]
I am going to close this issue. Could you please speak to Danilo about this and then let us know when you have the "final" wording and then open the ticket again?
