### ISSUE TITLE
Mobile App: Number of requests in search results

### ISSUE THREAD

**Issue by likeawesome** [spicygreenbook/greenbook-app#92]
After a search is made we may want to specify what the number of "matches" means. Standard language is "[x] results" and showing the search terms that were used. 

Alternatively, we could use language that's more specific to SGB like "12 Black-owned results" to reiterate the site's purpose. I noticed the after the homepage the language around supporting Black-owned businesses fades away.

![iOS14-2-iPhone11_7639](https://user-images.githubusercontent.com/74067650/98839936-7288c580-2403-11eb-9341-f18a04a936db.jpg)

**Comment by danilobatson** [comment]
I like the idea of "12 Black-owned results"
