### ISSUE TITLE
Press Kit Delay

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#93]
The press kit link on the "about" page takes a very long time to load. Anyway to optimize this? 

Can we also include a link to the press kit in the footer? 

<img width="1440" alt="Screen Shot 2020-11-11 at 9 12 09 AM" src="https://user-images.githubusercontent.com/69876068/98842228-1cfdea00-23fe-11eb-9846-d20164893f9e.png">

[SGB Press Kit.pdf](https://github.com/spicygreenbook/greenbook-app/files/5525632/SGB.Press.Kit.pdf)

**Comment by pleaseshutup** [comment]
The provided press kit is 7 MB 

If you want it faster you need to provide a smaller PDF.

The current design footer does not allow for room for any more links in the footer alongside the existing ones. if you like we can just add it after the logos of our partners on the bottom and just throw all kinds of extra s*** there.

**Comment by danilobatson** [comment]
I already compressed it from like 30+ MB lol 

Yea we can put it there after the logos

**Comment by pleaseshutup** [comment]
added in 4bc313fbe5b56c5636dd13b1a759241188f3c37d
