### ISSUE TITLE
RE:store Logo 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#95]
Can we include this logo at the bottom of the homepage where the other logos exist

![RestoreLA-Logo Black](https://user-images.githubusercontent.com/69876068/98859420-03b56780-2417-11eb-81a6-12facf0838d6.png)

<img width="1440" alt="Screen Shot 2020-11-11 at 12 13 18 PM" src="https://user-images.githubusercontent.com/69876068/98859711-6eff3980-2417-11eb-911d-61e9bade063d.png">

**Comment by pleaseshutup** [comment]
Can you link to their branding page and/or find us the logo in white with a transparent background? SVG will also work fine.

**Comment by danilobatson** [comment]
![image](https://user-images.githubusercontent.com/69876068/98997417-54959080-24e9-11eb-95a7-5e6da055dea7.png)

**Comment by pleaseshutup** [comment]
Done
